In [241]:
################################################
#                                              #
#        0) FUNCTION FOR PREPROCESSING         #
#                                              #
################################################

In [4]:
#!pip install pandas
#!pip install numpy
import pandas as pd
import numpy as np

In [37]:
import sys
sys.path.append('../')
from func import *

In [7]:
#DEFINED FUNCTIONS :
    
#unique_clean(data,col,pr=0)

#df_with_text(data,col,text)
#text_in_df(data,col,text)
#two_text_in_df(data,col,text1,text2)
#two_text_in_df(data,col,text1,text2='')

#values_U_not_nan(data,col_name)
#not_nan_get_values(data,col_name,pr=0)
#not_nan_get_index(data, col_name, pr=0)
#nan_get_index(data, col_name, pr=0)

#is_not_decimal(a)
#is_not_13(a)
#split_text_left(text_to_split,text)
#split_item_left(st)
#split_item_right(st)

#find_weight(text):     #s = re.compile('\d+G') extracts '210G'

In [ ]:
################################################
#                                              #
#        1) LOAD NIELSEN DATA                  #
#                                              #
################################################

In [12]:
data = pd.read_excel('input_data/Data_Nielsen_ALL.xlsx',usecols=range(3,42),header=0)
print('done')

done

In [13]:
data.shape

(209040, 51)

In [13]:
data.rename(columns={'MARKET.1': 'MARKET_INITIAL'},inplace=True)

In [39]:
data['NIELSEN_DESCRIPTION'] = data['NIELSEN_DESCRIPTION'].str.replace('-0E50', '*', regex=True, case=False)

In [17]:
#CREATION OF NEW COLUMNS TO STORE DATA

#!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!#
#                                              #
#         DO NOT EXECUTE TWICE  !!!!!          #
#                                              #
#!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
data['EAN13']=data['ITEM'].copy()
data['MARKET']=''
data['KPI']=''
data['CATEGORY']=''
data['ORGANIC']=''
data['WEIGHT']=''
data['INITIAL_INDEX']=data['NIELSEN_DESCRIPTION'].index

In [18]:
data[['ITEM','EAN13','MARKET','KPI','CATEGORY','ORGANIC','WEIGHT','INITIAL_INDEX']].info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 209040 entries, 0 to 209039
Data columns (total 8 columns):
ITEM             194752 non-null object
EAN13            194752 non-null object
MARKET           209040 non-null object
KPI              209040 non-null object
CATEGORY         209040 non-null object
ORGANIC          209040 non-null object
WEIGHT           209040 non-null object
INITIAL_INDEX    209040 non-null int64
dtypes: int64(1), object(7)
memory usage: 12.8+ MB

In [14]:
data['NIELSEN_DESCRIPTION'][2000]

'FECULENTS POT AUT FAB AUT MQ BOLO ORIGINALE MF BOLOG BASI 1CT 400G * NON BIO'

In [15]:
data.head(20)

,MARKET_INITIAL,FACTS,NIELSEN_DESCRIPTION,EMBALLAGE,MARQUE,GAMME,FORMAT,RECETTES,COMPTE,STD/PROMO,...,4 S 21/04/19,4 S 19/05/19,4 S 16/06/19,4 S 14/07/19,4 S 11/08/19,4 S 08/09/19,4 S 06/10/19,4 S 03/11/19,4 S 01/12/19,4 S 29/12/19
0,HMSM + PROXI + DRIVE + SDMP,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,Ventes Volume,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,AUT SCE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,33094.2,44605.2,42718.4,48412.6,34205.7,42914.3,40980.1,42130.6,56423.4,40516.4
3,NaN,NaN,AUT SCE AUT EMB,AUT EMB,NaN,NaN,NaN,NaN,NaN,NaN,...,46.4,59.7,48.6,49.6,60.6,65.7,83.8,183.4,321.5,259.5
4,NaN,NaN,AUT SCE AUT EMB AUT MQ,AUT EMB,AUT MQ,NaN,NaN,NaN,NaN,NaN,...,46.4,59.7,48.6,49.6,60.6,65.7,83.8,183.4,321.5,259.5
5,NaN,NaN,AUT EMB AUT FAB AUT MQ SCE CLAS PF CITRON VERT...,AUT EMB,AUT MQ,SCE CLAS,PF,CITRON VERT PIMENT DOUX,1CT,STD,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
6,NaN,NaN,AUT SCE AUT EMB AUT FAB AUT MQ SCE CLAS PF CUR...,AUT EMB,AUT MQ,SCE CLAS,PF,CURRY JAUNE THAI,1CT,STD,...,46.4,59.7,48.6,49.6,60.6,65.7,62.2,67.5,57.0,59.1
7,NaN,NaN,SCE AUT EMB AUT FAB AUT MQ SCE CLAS PF CURRY V...,AUT EMB,AUT MQ,SCE CLAS,PF,CURRY VERT & LEGUMES,1CT,STD,...,0.0,0.0,0.0,0.0,0.0,0.0,21.6,116.0,264.5,200.4
8,NaN,NaN,AUT SCE AUT EMB AUT FAB AUT MQ SCE CLAS PF YUZ...,AUT EMB,AUT MQ,SCE CLAS,PF,YUZU,1CT,STD,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
9,NaN,NaN,AUT SCE BRIC,BRIC,NaN,NaN,NaN,NaN,NaN,NaN,...,512.5,1902.0,2448.4,1919.4,2411.1,3074.9,3450.2,3967.2,4359.5,6877.4
10,NaN,NaN,AUT SCE BRIC MDD,BRIC,MDD,NaN,NaN,NaN,NaN,NaN,...,512.5,1902.0,2448.4,1919.4,2411.1,3074.9,3450.2,3967.2,4359.5,6877.4
11,NaN,NaN,AUT SCE BTE FER,BTE FER,NaN,NaN,NaN,NaN,NaN,NaN,...,41.0,33.6,36.8,20.1,41.0,46.4,43.0,53.4,56.6,426.1
12,NaN,NaN,AUT SCE BTE FER AUT MQ,BTE FER,AUT MQ,NaN,NaN,NaN,NaN,NaN,...,41.0,33.6,36.8,20.1,41.0,46.4,43.0,53.4,56.6,426.1
13,NaN,NaN,FER AUT FAB AUT MQ SCE CLAS PF CEPES & AU JUS ...,BTE FER,AUT MQ,SCE CLAS,PF,CEPES & AU JUS DE TRUFFES NOIR,1CT,STD,...,26.8,20.4,21.2,12.1,25.6,30.8,27.4,31.0,38.6,303.3
14,NaN,NaN,SCE BTE FER AUT FAB AUT MQ SCE CLAS PF PERIGUE...,BTE FER,AUT MQ,SCE CLAS,PF,PERIGUEUX TRUFFEE A 1%,1CT,STD,...,14.2,13.2,15.6,8.0,15.4,15.6,15.6,22.4,18.0,122.8
15,NaN,NaN,AUT SCE DOSE,DOSE,NaN,NaN,NaN,NaN,NaN,NaN,...,305.1,311.0,296.5,254.2,309.1,310.5,340.4,390.7,578.4,1191.0
16,NaN,NaN,AUT SCE DOSE AUT MQ,DOSE,AUT MQ,NaN,NaN,NaN,NaN,NaN,...,305.1,311.0,296.5,254.2,309.1,310.5,340.4,390.7,578.4,1191.0
17,NaN,NaN,DOSE AUT FAB AUT MQ SCE CLAS FI BEURRE BLANC &...,DOSE,AUT MQ,SCE CLAS,FI,BEURRE BLANC & CITRON CONFIT,3CT,STD,...,196.2,206.9,193.3,149.6,179.6,172.4,184.2,195.6,227.3,288.4
18,NaN,NaN,AUT SCE DOSE AUT FAB AUT MQ SCE CLAS FI CEPE 3...,DOSE,AUT MQ,SCE CLAS,FI,CEPE,3CT,STD,...,12.2,27.9,36.3,59.9,82.4,96.3,132.2,164.0,214.6,450.8
19,NaN,NaN,AUT SCE DOSE AUT FAB AUT MQ SCE CLAS FI CREME ...,DOSE,AUT MQ,SCE CLAS,FI,CREME AUX POIREAUX,3CT,STD,...,65.4,55.2,46.1,27.9,33.3,29.1,17.4,15.9,45.9,75.0

In [16]:
data.keys()

Index(['MARKET_INITIAL', 'FACTS', 'NIELSEN_DESCRIPTION', 'EMBALLAGE', 'MARQUE',
       'GAMME', 'FORMAT', 'RECETTES', 'COMPTE', 'STD/PROMO', 'ITEM',
       'CAM AN-1', 'DERNIER CAM', '4 S 28/01/18', '4 S 25/02/18',
       '4 S 25/03/18', '4 S 22/04/18', '4 S 20/05/18', '4 S 17/06/18',
       '4 S 15/07/18', '4 S 12/08/18', '4 S 09/09/18', '4 S 07/10/18',
       '4 S 04/11/18', '4 S 02/12/18', '4 S 30/12/18', '4 S 27/01/19',
       '4 S 24/02/19', '4 S 24/03/19', '4 S 21/04/19', '4 S 19/05/19',
       '4 S 16/06/19', '4 S 14/07/19', '4 S 11/08/19', '4 S 08/09/19',
       '4 S 06/10/19', '4 S 03/11/19', '4 S 01/12/19', '4 S 29/12/19'],
      dtype='object')

In [17]:
text_in_df( data,'NIELSEN_DESCRIPTION',' FER ')

text "  FER  appears 9656 lines, in 70 different values

                                                    0
0                              AUT SCE BTE FER AUT MQ
1   SCE BTE FER AUT FAB AUT MQ SCE CLAS PF PERIGUE...
2                SAUCES POUR FECULENTS BTE FER AUT MQ
3   POUR FECULENTS BTE FER AUT FAB AUT MQ AUT VIAN...
4   BTE FER AUT FAB AUT MQ AUTRE GAMME PF GIROLLE ...
..                                                ...
65  BTE FER ZAPETTI ZAPETTI BUITONI LEGUMES PF PRO...
66  BTE FER ZAPETTI ZAPETTI BUITONI LEGUMES PF PRO...
67  BTE FER ZAPETTI ZAPETTI BUITONI LEGUMES PF PRO...
68  BTE FER ZAPETTI ZAPETTI BUITONI LEGUMES PF RAT...
69  BTE FER ZAPETTI ZAPETTI BUITONI LEGUMES PF RAT...

[70 rows x 1 columns]

In [21]:
df_with_text(data,'NIELSEN_DESCRIPTION','^FER').head()

,MARKET_INITIAL,FACTS,NIELSEN_DESCRIPTION,EMBALLAGE,MARQUE,GAMME,FORMAT,RECETTES,COMPTE,STD/PROMO,...,4 S 03/11/19,4 S 01/12/19,4 S 29/12/19,EAN13,MARKET,KPI,CATEGORY,ORGANIC,WEIGHT,INITIAL_INDEX
13,NaN,NaN,FER AUT FAB AUT MQ SCE CLAS PF CEPES & AU JUS ...,BTE FER,AUT MQ,SCE CLAS,PF,CEPES & AU JUS DE TRUFFES NOIR,1CT,STD,...,31.0,38.6,303.3,3416952625159,,,,,,13
255,NaN,NaN,FER ZAPETTI ZAPETTI BUITONI BOLO CLASSIQUE MF ...,BTE FER,ZAPETTI BUITONI,BOLO CLASSIQUE,MF,ITALIEN,2CT,PROMO,...,0.0,0.0,0.0,3021690023701,,,,,,255
262,NaN,NaN,FER ZAPETTI ZAPETTI BUITONI BOLO CLASSIQUE PF ...,BTE FER,ZAPETTI BUITONI,BOLO CLASSIQUE,PF,ITALIEN,3CT,PROMO,...,8017.6,18873.1,15892.0,3021690021059,,,,,,262
274,NaN,NaN,FER ZAPETTI ZAPETTI BUITONI LEGUMES PF PROVENC...,BTE FER,ZAPETTI BUITONI,LEGUMES,PF,PROVENC LANGUE,2CT,PROMO,...,41.8,25.8,12.5,3021690021981,,,,,,274
275,NaN,NaN,FER ZAPETTI ZAPETTI BUITONI LEGUMES PF PROVENC...,BTE FER,ZAPETTI BUITONI,LEGUMES,PF,PROVENC LANGUE,4CT,PROMO,...,4750.4,2599.0,1786.7,3021690023657,,,,,,275

In [18]:
text_in_df(data,'NIELSEN_DESCRIPTION','^FER')

text " ^FER appears 680 lines, in 5 different values

                                                   0
0  FER AUT FAB AUT MQ SCE CLAS PF CEPES & AU JUS ...
1  FER ZAPETTI ZAPETTI BUITONI BOLO CLASSIQUE MF ...
2  FER ZAPETTI ZAPETTI BUITONI BOLO CLASSIQUE PF ...
3  FER ZAPETTI ZAPETTI BUITONI LEGUMES PF PROVENC...
4  FER ZAPETTI ZAPETTI BUITONI LEGUMES PF PROVENC...

In [19]:
two_text_in_df(data,'NIELSEN_DESCRIPTION','FER','BIO')

first text " FER " alone appears 10744 lines, in 78 different values and with
text " BIO appears 64 lines, in 64 different values

                                                    0
0   FER AUT FAB AUT MQ SCE CLAS PF CEPES & AU JUS ...
1   SCE BTE FER AUT FAB AUT MQ SCE CLAS PF PERIGUE...
2   POUR FECULENTS BTE FER AUT FAB AUT MQ AUT VIAN...
3   BTE FER AUT FAB AUT MQ AUTRE GAMME PF GIROLLE ...
4   POUR FECULENTS BTE FER AUT FAB AUT MQ CREME MF...
..                                                ...
59  FER ZAPETTI ZAPETTI BUITONI LEGUMES PF PROVENC...
60  BTE FER ZAPETTI ZAPETTI BUITONI LEGUMES PF PRO...
61  BTE FER ZAPETTI ZAPETTI BUITONI LEGUMES PF RAT...
62  BTE FER ZAPETTI ZAPETTI BUITONI LEGUMES PF RAT...
63  SAUCES POUR FECULENTS POT SACLA PESTO PF PESTO...

[64 rows x 1 columns]

In [20]:
text_in_df(data,'NIELSEN_DESCRIPTION','\* bio')

text " \* bio appears 23800 lines, in 166 different values

                                                     0
0    AUT SCE DOY PAC AUT FAB AUT MQ SCE CLAS PF ALG...
1    SCE DOY PAC AUT FAB AUT MQ SCE CLAS PF ALGUES ...
2    DOY PAC AUT FAB AUT MQ SCE CLAS PF CITRON VERT...
3    AUT SCE POT AUT FAB AUT MQ SCE CLAS MF CURRY T...
4    AUT SCE POT AUT FAB AUT MQ SCE CLAS MF TIKKA M...
..                                                 ...
161  POUR FECULENTS POT ZAPETTI ZAPETTI BUITONI BIO...
162  SAUCES POUR FECULENTS TUB AUT FAB AUT MQ BIO P...
163  SAUCES POUR FECULENTS TUB AUT FAB JARDIN BIO B...
164  TUB AUT FAB JARDIN BIO BIO PF TOMATE CUISINEE ...
165  POUR FECULENTS TUB PANZANI SA PANZANI BIO PF P...

[166 rows x 1 columns]

In [21]:
temp = text_in_df(data,'NIELSEN_DESCRIPTION','FER')
temp

text " FER appears 10744 lines, in 78 different values

                                                    0
0                                     AUT SCE BTE FER
1                              AUT SCE BTE FER AUT MQ
2   FER AUT FAB AUT MQ SCE CLAS PF CEPES & AU JUS ...
3   SCE BTE FER AUT FAB AUT MQ SCE CLAS PF PERIGUE...
4                       SAUCES POUR FECULENTS BTE FER
..                                                ...
73  FER ZAPETTI ZAPETTI BUITONI LEGUMES PF PROVENC...
74  BTE FER ZAPETTI ZAPETTI BUITONI LEGUMES PF PRO...
75  BTE FER ZAPETTI ZAPETTI BUITONI LEGUMES PF RAT...
76  BTE FER ZAPETTI ZAPETTI BUITONI LEGUMES PF RAT...
77  SAUCES POUR FECULENTS POT SACLA PESTO PF PESTO...

[78 rows x 1 columns]

In [22]:
text_in_df(temp,0,'\* bio')

text " \* bio appears 2 lines, in 2 different values

                                                   0
0  POUR FECULENTS BTE FER ZAPETTI ZAPETTI BUITONI...
1  POUR FECULENTS BTE FER ZAPETTI ZAPETTI BUITONI...

In [23]:
U = unique_clean(data,'MARKET_INITIAL',1) #0 default does not print 1 prints

HMSM + PROXI + DRIVE + SDMP
ENSEIGNES HMSM
ENSEIGNES SM
SM / MAGS < 2000 M2
SM / MAGS > 2000 M2
REGION 1 IDF (HMSM)
MONOPRIX
FRANPRIX

number of  MARKET_INITIAL  unique (non null) values:  8
<class 'list'>

In [24]:
#KPI_index=not_nan_get_index(data,'FACTS',1)
not_nan_get_index(data,'FACTS')

Int64Index([     1,   1538,   3075,   4612,   6149,   7686,   9223,  10760,
             12297,  13834,
            ...
            193670, 195207, 196744, 198281, 199818, 201355, 202892, 204429,
            205966, 207503],
           dtype='int64', length=136)

In [ ]:
data.head(20)

In [256]:
############################################################
#     2. CREATION OF EAN13 COLUMNS AND                     #
#     EXTRACTION OF LIST OF UNIQUE EAN13 PRODUCT CODES     #
############################################################

In [ ]:
#----------------------------------------------------------
# 2.1 GET UNIQUE EAN13

ITEM = data['ITEM'].unique()
N_ITEM = len(ITEM)
ITEM = ITEM[1:]
print('number of items',N_ITEM)
print('Il y a ', len(ITEM),' EAN13 dans la basse NIELSEN\n')
print(type(ITEM),'\n')
print(ITEM[0:20])
print(ITEM[-20:])

In [ ]:
# "VECTOR FUNCTION" TO CHECK IF ALL VALUE IN NP ARRAY ARE DECIMAL VLAUES
def is_not_decimal(a):
    return not np.char.isdecimal(a)

v_is_not_decimal = np.vectorize(is_not_decimal)
PB_num=v_is_not_decimal(ITEM)
print('number of EAN with non numerical values',PB_num.sum())
ITEM[PB_num]

In [259]:
v_is_not_13 = np.vectorize(is_not_13)
PB_13=v_is_not_13(ITEM)
print('number of EAN which do not have 13 digits',PB_13.sum())
ITEM[PB_13]

number of EAN which do not have 13 digits 15

array(['3183811010837BP2', '3183811010837BP1', '3337730000510BP1',
       '3038354197500BP1', '3038354197104BP1', '3038359004605BP1',
       '3038359004629BP1', '3038359007712BP1', '3038359007699BP2',
       '3038359007699BP1', '3038354197500BP2', '3038359004629BP2',
       '3038359007712BP2', '3038354197104BP2', '3038359004605BP2'],
      dtype=object)

In [260]:
if np.equal(ITEM[PB_13],ITEM[PB_num]).sum()==len(ITEM[PB_13]):
    print('\nOK ! all issues with length and nunmerical values relate to the same ITEMS')
else:
    print('not OK, check your EAN13 column again')

OK ! all issues with length and nunmerical values relate to the same ITEMS

In [261]:
for p in ITEM[PB_num]:
    print('\nEAN13 :',p)
    print(data[data['ITEM']==p][['STD/PROMO','MARQUE','NIELSEN_DESCRIPTION']])
    
# TOUS LES EAN13 A 16 CHIFFRES CORRESPONDENT A DES PROMOS (beaucoup de Panzani !lol!)
# 136 occurences = 8 markets x 17 KPIs (column 'FACT')

EAN13 : 3183811010837BP2
       STD/PROMO  MARQUE                                NIELSEN_DESCRIPTION
737        PROMO  AUT MQ  POT AUT FAB AUT MQ LEGUMES PF TOMATE AIL & HER...
2274       PROMO  AUT MQ  POT AUT FAB AUT MQ LEGUMES PF TOMATE AIL & HER...
3811       PROMO  AUT MQ  POT AUT FAB AUT MQ LEGUMES PF TOMATE AIL & HER...
5348       PROMO  AUT MQ  POT AUT FAB AUT MQ LEGUMES PF TOMATE AIL & HER...
6885       PROMO  AUT MQ  POT AUT FAB AUT MQ LEGUMES PF TOMATE AIL & HER...
...          ...     ...                                                ...
202091     PROMO  AUT MQ  POT AUT FAB AUT MQ LEGUMES PF TOMATE AIL & HER...
203628     PROMO  AUT MQ  POT AUT FAB AUT MQ LEGUMES PF TOMATE AIL & HER...
205165     PROMO  AUT MQ  POT AUT FAB AUT MQ LEGUMES PF TOMATE AIL & HER...
206702     PROMO  AUT MQ  POT AUT FAB AUT MQ LEGUMES PF TOMATE AIL & HER...
208239     PROMO  AUT MQ  POT AUT FAB AUT MQ LEGUMES PF TOMATE AIL & HER...

[136 rows x 3 columns]

EAN13 : 3183811010837BP1
       STD/PROMO  MARQUE                                NIELSEN_DESCRIPTION
740        PROMO  AUT MQ  FECULENTS POT AUT FAB AUT MQ LEGUMES PF TOMATE...
2277       PROMO  AUT MQ  FECULENTS POT AUT FAB AUT MQ LEGUMES PF TOMATE...
3814       PROMO  AUT MQ  FECULENTS POT AUT FAB AUT MQ LEGUMES PF TOMATE...
5351       PROMO  AUT MQ  FECULENTS POT AUT FAB AUT MQ LEGUMES PF TOMATE...
6888       PROMO  AUT MQ  FECULENTS POT AUT FAB AUT MQ LEGUMES PF TOMATE...
...          ...     ...                                                ...
202094     PROMO  AUT MQ  FECULENTS POT AUT FAB AUT MQ LEGUMES PF TOMATE...
203631     PROMO  AUT MQ  FECULENTS POT AUT FAB AUT MQ LEGUMES PF TOMATE...
205168     PROMO  AUT MQ  FECULENTS POT AUT FAB AUT MQ LEGUMES PF TOMATE...
206705     PROMO  AUT MQ  FECULENTS POT AUT FAB AUT MQ LEGUMES PF TOMATE...
208242     PROMO  AUT MQ  FECULENTS POT AUT FAB AUT MQ LEGUMES PF TOMATE...

[136 rows x 3 columns]

EAN13 : 3337730000510BP1
       STD/PROMO  MARQUE                                NIELSEN_DESCRIPTION
795        PROMO  AUT MQ  SAUCES POUR FECULENTS POT AUT FAB AUT MQ PESTO...
2332       PROMO  AUT MQ  SAUCES POUR FECULENTS POT AUT FAB AUT MQ PESTO...
3869       PROMO  AUT MQ  SAUCES POUR FECULENTS POT AUT FAB AUT MQ PESTO...
5406       PROMO  AUT MQ  SAUCES POUR FECULENTS POT AUT FAB AUT MQ PESTO...
6943       PROMO  AUT MQ  SAUCES POUR FECULENTS POT AUT FAB AUT MQ PESTO...
...          ...     ...                                                ...
202149     PROMO  AUT MQ  SAUCES POUR FECULENTS POT AUT FAB AUT MQ PESTO...
203686     PROMO  AUT MQ  SAUCES POUR FECULENTS POT AUT FAB AUT MQ PESTO...
205223     PROMO  AUT MQ  SAUCES POUR FECULENTS POT AUT FAB AUT MQ PESTO...
206760     PROMO  AUT MQ  SAUCES POUR FECULENTS POT AUT FAB AUT MQ PESTO...
208297     PROMO  AUT MQ  SAUCES POUR FECULENTS POT AUT FAB AUT MQ PESTO...

[136 rows x 3 columns]

EAN13 : 3038354197500BP1
       STD/PROMO   MARQUE                                NIELSEN_DESCRIPTION
1211       PROMO  PANZANI  FECULENTS POT PANZANI SA PANZANI BOLO CLASSIQU...
2748       PROMO  PANZANI  FECULENTS POT PANZANI SA PANZANI BOLO CLASSIQU...
4285       PROMO  PANZANI  FECULENTS POT PANZANI SA PANZANI BOLO CLASSIQU...
5822       PROMO  PANZANI  FECULENTS POT PANZANI SA PANZANI BOLO CLASSIQU...
7359       PROMO  PANZANI  FECULENTS POT PANZANI SA PANZANI BOLO CLASSIQU...
...          ...      ...                                                ...
202565     PROMO  PANZANI  FECULENTS POT PANZANI SA PANZANI BOLO CLASSIQU...
204102     PROMO  PANZANI  FECULENTS POT PANZANI SA PANZANI BOLO CLASSIQU...
205639     PROMO  PANZANI  FECULENTS POT PANZANI SA PANZANI BOLO CLASSIQU...
207176     PROMO  PANZANI  FECULENTS POT PANZANI SA PANZANI BOLO CLASSIQU...
208713     PROMO  PANZANI  FECULENTS POT PANZANI SA PANZANI BOLO CLASSIQU...

[136 rows x 3 columns]

EAN13 : 3038354197104BP1
       STD/PROMO   MARQUE                                NIELSEN_DESCRIPTION
1212       PROMO  PANZANI  FECULENTS POT PANZANI SA PANZANI BOLO CLASSIQU...
2749       PROMO  PANZANI  FECULENTS POT PANZANI SA PANZANI BOLO CLASSIQU...
4286       PROMO  PANZANI  FECULENTS POT PANZANI SA PANZANI BOLO CLASSIQU...
5823       PROMO  PANZANI  FECULENTS POT PANZANI SA PANZANI BOLO CLASSIQU...
7360       PROMO  PANZANI  FECULENTS POT PANZANI SA PANZANI BOLO CLASSIQU...
...          ...      ...                                                ...
202566     PROMO  PANZANI  FECULENTS POT PANZANI SA PANZANI BOLO CLASSIQU...
204103     PROMO  PANZANI  FECULENTS POT PANZANI SA PANZANI BOLO CLASSIQU...
205640     PROMO  PANZANI  FECULENTS POT PANZANI SA PANZANI BOLO CLASSIQU...
207177     PROMO  PANZANI  FECULENTS POT PANZANI SA PANZANI BOLO CLASSIQU...
208714     PROMO  PANZANI  FECULENTS POT PANZANI SA PANZANI BOLO CLASSIQU...

[136 rows x 3 columns]

EAN13 : 3038359004605BP1
       STD/PROMO   MARQUE                                NIELSEN_DESCRIPTION
1213       PROMO  PANZANI  FECULENTS POT PANZANI SA PANZANI BOLO CLASSIQU...
2750       PROMO  PANZANI  FECULENTS POT PANZANI SA PANZANI BOLO CLASSIQU...
4287       PROMO  PANZANI  FECULENTS POT PANZANI SA PANZANI BOLO CLASSIQU...
5824       PROMO  PANZANI  FECULENTS POT PANZANI SA PANZANI BOLO CLASSIQU...
7361       PROMO  PANZANI  FECULENTS POT PANZANI SA PANZANI BOLO CLASSIQU...
...          ...      ...                                                ...
202567     PROMO  PANZANI  FECULENTS POT PANZANI SA PANZANI BOLO CLASSIQU...
204104     PROMO  PANZANI  FECULENTS POT PANZANI SA PANZANI BOLO CLASSIQU...
205641     PROMO  PANZANI  FECULENTS POT PANZANI SA PANZANI BOLO CLASSIQU...
207178     PROMO  PANZANI  FECULENTS POT PANZANI SA PANZANI BOLO CLASSIQU...
208715     PROMO  PANZANI  FECULENTS POT PANZANI SA PANZANI BOLO CLASSIQU...

[136 rows x 3 columns]

EAN13 : 3038359004629BP1
       STD/PROMO   MARQUE                                NIELSEN_DESCRIPTION
1214       PROMO  PANZANI  FECULENTS POT PANZANI SA PANZANI BOLO CLASSIQU...
2751       PROMO  PANZANI  FECULENTS POT PANZANI SA PANZANI BOLO CLASSIQU...
4288       PROMO  PANZANI  FECULENTS POT PANZANI SA PANZANI BOLO CLASSIQU...
5825       PROMO  PANZANI  FECULENTS POT PANZANI SA PANZANI BOLO CLASSIQU...
7362       PROMO  PANZANI  FECULENTS POT PANZANI SA PANZANI BOLO CLASSIQU...
...          ...      ...                                                ...
202568     PROMO  PANZANI  FECULENTS POT PANZANI SA PANZANI BOLO CLASSIQU...
204105     PROMO  PANZANI  FECULENTS POT PANZANI SA PANZANI BOLO CLASSIQU...
205642     PROMO  PANZANI  FECULENTS POT PANZANI SA PANZANI BOLO CLASSIQU...
207179     PROMO  PANZANI  FECULENTS POT PANZANI SA PANZANI BOLO CLASSIQU...
208716     PROMO  PANZANI  FECULENTS POT PANZANI SA PANZANI BOLO CLASSIQU...

[136 rows x 3 columns]

EAN13 : 3038359007712BP1
       STD/PROMO   MARQUE                                NIELSEN_DESCRIPTION
1222       PROMO  PANZANI  POT PANZANI SA PANZANI BOLO CLASSIQUE PF BOLOG...
2759       PROMO  PANZANI  POT PANZANI SA PANZANI BOLO CLASSIQUE PF BOLOG...
4296       PROMO  PANZANI  POT PANZANI SA PANZANI BOLO CLASSIQUE PF BOLOG...
5833       PROMO  PANZANI  POT PANZANI SA PANZANI BOLO CLASSIQUE PF BOLOG...
7370       PROMO  PANZANI  POT PANZANI SA PANZANI BOLO CLASSIQUE PF BOLOG...
...          ...      ...                                                ...
202576     PROMO  PANZANI  POT PANZANI SA PANZANI BOLO CLASSIQUE PF BOLOG...
204113     PROMO  PANZANI  POT PANZANI SA PANZANI BOLO CLASSIQUE PF BOLOG...
205650     PROMO  PANZANI  POT PANZANI SA PANZANI BOLO CLASSIQUE PF BOLOG...
207187     PROMO  PANZANI  POT PANZANI SA PANZANI BOLO CLASSIQUE PF BOLOG...
208724     PROMO  PANZANI  POT PANZANI SA PANZANI BOLO CLASSIQUE PF BOLOG...

[136 rows x 3 columns]

EAN13 : 3038359007699BP2
       STD/PROMO   MARQUE                                NIELSEN_DESCRIPTION
1223       PROMO  PANZANI  POT PANZANI SA PANZANI BOLO CLASSIQUE PF BOLOG...
2760       PROMO  PANZANI  POT PANZANI SA PANZANI BOLO CLASSIQUE PF BOLOG...
4297       PROMO  PANZANI  POT PANZANI SA PANZANI BOLO CLASSIQUE PF BOLOG...
5834       PROMO  PANZANI  POT PANZANI SA PANZANI BOLO CLASSIQUE PF BOLOG...
7371       PROMO  PANZANI  POT PANZANI SA PANZANI BOLO CLASSIQUE PF BOLOG...
...          ...      ...                                                ...
202577     PROMO  PANZANI  POT PANZANI SA PANZANI BOLO CLASSIQUE PF BOLOG...
204114     PROMO  PANZANI  POT PANZANI SA PANZANI BOLO CLASSIQUE PF BOLOG...
205651     PROMO  PANZANI  POT PANZANI SA PANZANI BOLO CLASSIQUE PF BOLOG...
207188     PROMO  PANZANI  POT PANZANI SA PANZANI BOLO CLASSIQUE PF BOLOG...
208725     PROMO  PANZANI  POT PANZANI SA PANZANI BOLO CLASSIQUE PF BOLOG...

[136 rows x 3 columns]

EAN13 : 3038359007699BP1
       STD/PROMO   MARQUE                                NIELSEN_DESCRIPTION
1288       PROMO  PANZANI  POUR FECULENTS POT PANZANI SA PANZANI LEGUMES ...
2825       PROMO  PANZANI  POUR FECULENTS POT PANZANI SA PANZANI LEGUMES ...
4362       PROMO  PANZANI  POUR FECULENTS POT PANZANI SA PANZANI LEGUMES ...
5899       PROMO  PANZANI  POUR FECULENTS POT PANZANI SA PANZANI LEGUMES ...
7436       PROMO  PANZANI  POUR FECULENTS POT PANZANI SA PANZANI LEGUMES ...
...          ...      ...                                                ...
202642     PROMO  PANZANI  POUR FECULENTS POT PANZANI SA PANZANI LEGUMES ...
204179     PROMO  PANZANI  POUR FECULENTS POT PANZANI SA PANZANI LEGUMES ...
205716     PROMO  PANZANI  POUR FECULENTS POT PANZANI SA PANZANI LEGUMES ...
207253     PROMO  PANZANI  POUR FECULENTS POT PANZANI SA PANZANI LEGUMES ...
208790     PROMO  PANZANI  POUR FECULENTS POT PANZANI SA PANZANI LEGUMES ...

[136 rows x 3 columns]

EAN13 : 3038354197500BP2
       STD/PROMO   MARQUE                                NIELSEN_DESCRIPTION
1297       PROMO  PANZANI  POUR FECULENTS POT PANZANI SA PANZANI LEGUMES ...
2834       PROMO  PANZANI  POUR FECULENTS POT PANZANI SA PANZANI LEGUMES ...
4371       PROMO  PANZANI  POUR FECULENTS POT PANZANI SA PANZANI LEGUMES ...
5908       PROMO  PANZANI  POUR FECULENTS POT PANZANI SA PANZANI LEGUMES ...
7445       PROMO  PANZANI  POUR FECULENTS POT PANZANI SA PANZANI LEGUMES ...
...          ...      ...                                                ...
202651     PROMO  PANZANI  POUR FECULENTS POT PANZANI SA PANZANI LEGUMES ...
204188     PROMO  PANZANI  POUR FECULENTS POT PANZANI SA PANZANI LEGUMES ...
205725     PROMO  PANZANI  POUR FECULENTS POT PANZANI SA PANZANI LEGUMES ...
207262     PROMO  PANZANI  POUR FECULENTS POT PANZANI SA PANZANI LEGUMES ...
208799     PROMO  PANZANI  POUR FECULENTS POT PANZANI SA PANZANI LEGUMES ...

[136 rows x 3 columns]

EAN13 : 3038359004629BP2
       STD/PROMO   MARQUE                                NIELSEN_DESCRIPTION
1298       PROMO  PANZANI  POUR FECULENTS POT PANZANI SA PANZANI LEGUMES ...
2835       PROMO  PANZANI  POUR FECULENTS POT PANZANI SA PANZANI LEGUMES ...
4372       PROMO  PANZANI  POUR FECULENTS POT PANZANI SA PANZANI LEGUMES ...
5909       PROMO  PANZANI  POUR FECULENTS POT PANZANI SA PANZANI LEGUMES ...
7446       PROMO  PANZANI  POUR FECULENTS POT PANZANI SA PANZANI LEGUMES ...
...          ...      ...                                                ...
202652     PROMO  PANZANI  POUR FECULENTS POT PANZANI SA PANZANI LEGUMES ...
204189     PROMO  PANZANI  POUR FECULENTS POT PANZANI SA PANZANI LEGUMES ...
205726     PROMO  PANZANI  POUR FECULENTS POT PANZANI SA PANZANI LEGUMES ...
207263     PROMO  PANZANI  POUR FECULENTS POT PANZANI SA PANZANI LEGUMES ...
208800     PROMO  PANZANI  POUR FECULENTS POT PANZANI SA PANZANI LEGUMES ...

[136 rows x 3 columns]

EAN13 : 3038359007712BP2
       STD/PROMO   MARQUE                                NIELSEN_DESCRIPTION
1299       PROMO  PANZANI  POUR FECULENTS POT PANZANI SA PANZANI LEGUMES ...
2836       PROMO  PANZANI  POUR FECULENTS POT PANZANI SA PANZANI LEGUMES ...
4373       PROMO  PANZANI  POUR FECULENTS POT PANZANI SA PANZANI LEGUMES ...
5910       PROMO  PANZANI  POUR FECULENTS POT PANZANI SA PANZANI LEGUMES ...
7447       PROMO  PANZANI  POUR FECULENTS POT PANZANI SA PANZANI LEGUMES ...
...          ...      ...                                                ...
202653     PROMO  PANZANI  POUR FECULENTS POT PANZANI SA PANZANI LEGUMES ...
204190     PROMO  PANZANI  POUR FECULENTS POT PANZANI SA PANZANI LEGUMES ...
205727     PROMO  PANZANI  POUR FECULENTS POT PANZANI SA PANZANI LEGUMES ...
207264     PROMO  PANZANI  POUR FECULENTS POT PANZANI SA PANZANI LEGUMES ...
208801     PROMO  PANZANI  POUR FECULENTS POT PANZANI SA PANZANI LEGUMES ...

[136 rows x 3 columns]

EAN13 : 3038354197104BP2
       STD/PROMO   MARQUE                                NIELSEN_DESCRIPTION
1303       PROMO  PANZANI  FECULENTS POT PANZANI SA PANZANI LEGUMES PF TO...
2840       PROMO  PANZANI  FECULENTS POT PANZANI SA PANZANI LEGUMES PF TO...
4377       PROMO  PANZANI  FECULENTS POT PANZANI SA PANZANI LEGUMES PF TO...
5914       PROMO  PANZANI  FECULENTS POT PANZANI SA PANZANI LEGUMES PF TO...
7451       PROMO  PANZANI  FECULENTS POT PANZANI SA PANZANI LEGUMES PF TO...
...          ...      ...                                                ...
202657     PROMO  PANZANI  FECULENTS POT PANZANI SA PANZANI LEGUMES PF TO...
204194     PROMO  PANZANI  FECULENTS POT PANZANI SA PANZANI LEGUMES PF TO...
205731     PROMO  PANZANI  FECULENTS POT PANZANI SA PANZANI LEGUMES PF TO...
207268     PROMO  PANZANI  FECULENTS POT PANZANI SA PANZANI LEGUMES PF TO...
208805     PROMO  PANZANI  FECULENTS POT PANZANI SA PANZANI LEGUMES PF TO...

[136 rows x 3 columns]

EAN13 : 3038359004605BP2
       STD/PROMO   MARQUE                                NIELSEN_DESCRIPTION
1304       PROMO  PANZANI  FECULENTS POT PANZANI SA PANZANI LEGUMES PF TO...
2841       PROMO  PANZANI  FECULENTS POT PANZANI SA PANZANI LEGUMES PF TO...
4378       PROMO  PANZANI  FECULENTS POT PANZANI SA PANZANI LEGUMES PF TO...
5915       PROMO  PANZANI  FECULENTS POT PANZANI SA PANZANI LEGUMES PF TO...
7452       PROMO  PANZANI  FECULENTS POT PANZANI SA PANZANI LEGUMES PF TO...
...          ...      ...                                                ...
202658     PROMO  PANZANI  FECULENTS POT PANZANI SA PANZANI LEGUMES PF TO...
204195     PROMO  PANZANI  FECULENTS POT PANZANI SA PANZANI LEGUMES PF TO...
205732     PROMO  PANZANI  FECULENTS POT PANZANI SA PANZANI LEGUMES PF TO...
207269     PROMO  PANZANI  FECULENTS POT PANZANI SA PANZANI LEGUMES PF TO...
208806     PROMO  PANZANI  FECULENTS POT PANZANI SA PANZANI LEGUMES PF TO...

[136 rows x 3 columns]

In [262]:
#-------------------------------------------------------------------------------
#-------------------------------------------------------------------------------
# 2.2 CREATION OF A COLUMN 'EAN13' WITH A STRING OF 13 DIGITS (REAL EAN13 PRODUCT CODES)
#(suppression of extra 3 digits)
nan_ITEM_index=nan_get_index(data, 'ITEM', pr=0)
not_nan_ITEM_index=not_nan_get_index(data, 'ITEM', pr=0)
data['EAN13'][nan_ITEM_index]='0'
data['EAN13'][not_nan_ITEM_index]=data['ITEM'][not_nan_ITEM_index].apply(lambda row:str(row)[0:13])
data['EAN13']

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  import sys
C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

0                     0
1                     0
2                     0
3                     0
4                     0
              ...
209035    3038359005657
209036                0
209037    3038359001413
209038                0
209039    3021690021851
Name: EAN13, Length: 209040, dtype: object

In [26]:
data['EAN_promo']=data['ITEM'].apply(lambda row:str(row)[13:])
nan_index_code_promo= nan_get_index(data, 'EAN_promo', pr=0)
#data[data['EAN_code_promo']=='']['EAN_code_promo']='0'
data['EAN_promo'].unique()

array(['', 'BP2', 'BP1'], dtype=object)

In [ ]:
check = data['EAN13'].apply(lambda row:len(row)!=13).sum()
check_nan = data[data['EAN13']=='nan'].shape[0]
print('All items in EAN13 column equal to NaN or 13 digit string:\n',check==check_nan)

In [ ]:
#-------------------------------------------------------------------------------
#-------------------------------------------------------------------------------
# 2.3 CREATE LIST WITH Unique EAN13 values to look up in Mongo BD 'Open food facts'
EAN13_U=data['EAN13'].unique()[1:]
print(type(EAN13_U))
print(type(EAN13_U[1]))
print('Number of unique EAN13 in database:',len(EAN13_U),'\n')
print(EAN13_U)

In [ ]:
#SAVE Unique EAN13 values to look up in Mongo BD 'Open food facts'
pd.DataFrame(EAN13_U).to_csv('output_data/N_EAN13_U.csv')

In [264]:
#save unique EAN13 values into a cvs file (string) for mongo db extract
#np.savetxt('/N_EAN13.csv',EAN13,fmt='%s')

In [265]:
#-------------------------------------------------------------------------------
#-------------------------------------------------------------------------------
# 2.4 création d'une liste d'EAN13 en valeur numérique 
data['EAN13_num']=data['EAN13'].copy()
data['EAN13_num']=data['EAN13_num'].astype(np.int64)
#data['EAN13_num']=data['EAN13_num'].astype(np.int64)
#print(data['EAN13_num'])

In [266]:
#-------------------------------------------------------------------------------
#-------------------------------------------------------------------------------
# 2.5 CHECK EAN13 IS CORRECTRLY HANDLED
data[['ITEM','EAN13','EAN_promo','EAN13_num']][0:10]

            ITEM          EAN13 EAN_promo      EAN13_num
0            NaN              0                        0
1            NaN              0                        0
2            NaN              0                        0
3            NaN              0                        0
4            NaN              0                        0
5  3760052155536  3760052155536            3760052155536
6  8854404005213  8854404005213            8854404005213
7  8858135071028  8858135071028            8858135071028
8  3760052155512  3760052155512            3760052155512
9            NaN              0                        0

In [268]:
#-------------------------------------------------------------------------------
#-------------------------------------------------------------------------------
# 2.7 FINAL CHECK FORMAT OF COLUMNS
data[['ITEM','EAN13','EAN13_num','SAME_PRODUCT','EAN_promo']].info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 209040 entries, 0 to 209039
Data columns (total 5 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   ITEM          194752 non-null  object
 1   EAN13         209040 non-null  object
 2   EAN13_num     209040 non-null  int64
 3   SAME_PRODUCT  194752 non-null  object
 4   EAN_promo     209040 non-null  object
dtypes: int64(1), object(4)
memory usage: 8.0+ MB

In [269]:
#data.drop(['WEIGHT_extract'],axis=1,inplace=True)
data.columns

Index(['MARKET_INITIAL', 'FACTS', 'NIELSEN_DESCRIPTION', 'EMBALLAGE', 'MARQUE',
       'GAMME', 'FORMAT', 'RECETTES', 'COMPTE', 'STD/PROMO', 'ITEM',
       'CAM AN-1', 'DERNIER CAM', '4 S 28/01/18', '4 S 25/02/18',
       '4 S 25/03/18', '4 S 22/04/18', '4 S 20/05/18', '4 S 17/06/18',
       '4 S 15/07/18', '4 S 12/08/18', '4 S 09/09/18', '4 S 07/10/18',
       '4 S 04/11/18', '4 S 02/12/18', '4 S 30/12/18', '4 S 27/01/19',
       '4 S 24/02/19', '4 S 24/03/19', '4 S 21/04/19', '4 S 19/05/19',
       '4 S 16/06/19', '4 S 14/07/19', '4 S 11/08/19', '4 S 08/09/19',
       '4 S 06/10/19', '4 S 03/11/19', '4 S 01/12/19', '4 S 29/12/19', 'EAN13',
       'MARKET', 'KPI', 'CATEGORY', 'ORGANIC', 'WEIGHT', 'INITIAL_INDEX',
       'EAN_promo', 'EAN13_num', 'SAME_PRODUCT'],
      dtype='object')

In [270]:
#data.drop(['WEIGHT_extract'],axis=1,inplace=True)

In [271]:
###################################################################
#     3. PROCESSING DATABASE STRUCTURE                            #
#     (Market, KPI, category)                                      #
###################################################################

In [272]:
data.head(10)

,MARKET_INITIAL,FACTS,NIELSEN_DESCRIPTION,EMBALLAGE,MARQUE,GAMME,FORMAT,RECETTES,COMPTE,STD/PROMO,...,EAN13,MARKET,KPI,CATEGORY,ORGANIC,WEIGHT,INITIAL_INDEX,EAN_promo,EAN13_num,SAME_PRODUCT
0,HMSM + PROXI + DRIVE + SDMP,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0,,,,,,0,,0,NaN
1,NaN,Ventes Volume,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0,,,,,,1,,0,NaN
2,NaN,NaN,AUT SCE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0,,,,,,2,,0,NaN
3,NaN,NaN,AUT SCE AUT EMB,AUT EMB,NaN,NaN,NaN,NaN,NaN,NaN,...,0,,,,,,3,,0,NaN
4,NaN,NaN,AUT SCE AUT EMB AUT MQ,AUT EMB,AUT MQ,NaN,NaN,NaN,NaN,NaN,...,0,,,,,,4,,0,NaN
5,NaN,NaN,AUT EMB AUT FAB AUT MQ SCE CLAS PF CITRON VERT...,AUT EMB,AUT MQ,SCE CLAS,PF,CITRON VERT PIMENT DOUX,1CT,STD,...,3760052155536,,,,,,5,,3760052155536,"AUT MQ, SCE CLAS, CITRON VERT PIMENT DOUX, AUT..."
6,NaN,NaN,AUT SCE AUT EMB AUT FAB AUT MQ SCE CLAS PF CUR...,AUT EMB,AUT MQ,SCE CLAS,PF,CURRY JAUNE THAI,1CT,STD,...,8854404005213,,,,,,6,,8854404005213,"AUT MQ, SCE CLAS, CURRY JAUNE THAI, AUT EMB,"
7,NaN,NaN,SCE AUT EMB AUT FAB AUT MQ SCE CLAS PF CURRY V...,AUT EMB,AUT MQ,SCE CLAS,PF,CURRY VERT & LEGUMES,1CT,STD,...,8858135071028,,,,,,7,,8858135071028,"AUT MQ, SCE CLAS, CURRY VERT & LEGUMES, AUT EMB,"
8,NaN,NaN,AUT SCE AUT EMB AUT FAB AUT MQ SCE CLAS PF YUZ...,AUT EMB,AUT MQ,SCE CLAS,PF,YUZU,1CT,STD,...,3760052155512,,,,,,8,,3760052155512,"AUT MQ, SCE CLAS, YUZU, AUT EMB,"
9,NaN,NaN,AUT SCE BRIC,BRIC,NaN,NaN,NaN,NaN,NaN,NaN,...,0,,,,,,9,,0,NaN

In [273]:
not_nan_get_values(data, 'MARKET',pr=0)

array([''], dtype=object)

In [274]:
#-------------------------------------------------------------------------------
#-------------------------------------------------------------------------------
# 3.1.FILL IN MARKET ON ALL LINES => COLUMN MARKET

#Check problem in that cell : virer les get_loc

market_index = not_nan_get_index(data, 'MARKET_INITIAL',pr=1) #liste des changment de market
#print(market_segment_index)

for i in range(len(market_index)):
    start = market_index[i]
    #market_segment_index.append(start)
    if i == len(market_index)-1:
        end = data.shape[0]
    else:
        end = market_index[i+1]
    data['MARKET'][start:end] = data['MARKET_INITIAL'][market_index[i]]


data.head()

number of non nan values: 8

index of not nan values:

 0         HMSM + PROXI + DRIVE + SDMP
26130                  ENSEIGNES HMSM
52260                    ENSEIGNES SM
78390             SM / MAGS < 2000 M2
104520            SM / MAGS > 2000 M2
130650            REGION 1 IDF (HMSM)
156780                       MONOPRIX
182910                       FRANPRIX
Name: MARKET_INITIAL, dtype: object

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

,MARKET_INITIAL,FACTS,NIELSEN_DESCRIPTION,EMBALLAGE,MARQUE,GAMME,FORMAT,RECETTES,COMPTE,STD/PROMO,...,EAN13,MARKET,KPI,CATEGORY,ORGANIC,WEIGHT,INITIAL_INDEX,EAN_promo,EAN13_num,SAME_PRODUCT
0,HMSM + PROXI + DRIVE + SDMP,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0,HMSM + PROXI + DRIVE + SDMP,,,,,0,,0,NaN
1,NaN,Ventes Volume,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0,HMSM + PROXI + DRIVE + SDMP,,,,,1,,0,NaN
2,NaN,NaN,AUT SCE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0,HMSM + PROXI + DRIVE + SDMP,,,,,2,,0,NaN
3,NaN,NaN,AUT SCE AUT EMB,AUT EMB,NaN,NaN,NaN,NaN,NaN,NaN,...,0,HMSM + PROXI + DRIVE + SDMP,,,,,3,,0,NaN
4,NaN,NaN,AUT SCE AUT EMB AUT MQ,AUT EMB,AUT MQ,NaN,NaN,NaN,NaN,NaN,...,0,HMSM + PROXI + DRIVE + SDMP,,,,,4,,0,NaN

In [275]:
market_segment_index

Int64Index([0, 26130, 52260, 78390, 104520, 130650, 156780, 182910], dtype='int64')

In [276]:
data[26130-3:26130+3]

,MARKET_INITIAL,FACTS,NIELSEN_DESCRIPTION,EMBALLAGE,MARQUE,GAMME,FORMAT,RECETTES,COMPTE,STD/PROMO,...,EAN13,MARKET,KPI,CATEGORY,ORGANIC,WEIGHT,INITIAL_INDEX,EAN_promo,EAN13_num,SAME_PRODUCT
26127,NaN,NaN,POUR FECULENTS TUB AUT FAB ZAKIA LEGUMES PF TO...,TUB,ZAKIA,LEGUMES,PF,TOMATE PIMENTE,1CT,STD,...,3038359001413,HMSM + PROXI + DRIVE + SDMP,,,,,26127,,3038359001413,"ZAKIA, LEGUMES, TOMATE PIMENTE, TUB,"
26128,NaN,NaN,SAUCES POUR FECULENTS TUB ZAPETTI BUITONI,TUB,ZAPETTI BUITONI,NaN,NaN,NaN,NaN,NaN,...,0,HMSM + PROXI + DRIVE + SDMP,,,,,26128,,0,NaN
26129,NaN,NaN,POUR FECULENTS TUB ZAPETTI ZAPETTI BUITONI LEG...,TUB,ZAPETTI BUITONI,LEGUMES,PF,NATURE,1CT,STD,...,3021690021851,HMSM + PROXI + DRIVE + SDMP,,,,,26129,,3021690021851,"ZAPETTI BUITONI, LEGUMES, NATURE, TUB,"
26130,ENSEIGNES HMSM,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0,ENSEIGNES HMSM,,,,,26130,,0,NaN
26131,NaN,Ventes Volume,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0,ENSEIGNES HMSM,,,,,26131,,0,NaN
26132,NaN,NaN,AUT SCE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0,ENSEIGNES HMSM,,,,,26132,,0,NaN

In [277]:
#-------------------------------------------------------------------------------
#-------------------------------------------------------------------------------
# 3.2.FILL IN FACTS ON ALL LINES => KPI

KPI_index = not_nan_get_index(data, 'FACTS', 1)

for i in range(len(KPI_index)) :
    start = KPI_index[i]
    
    if i == len(KPI_index)-1:
        end = data.shape[0]
    else:
        end = KPI_index[i+1]
    
    data['KPI'][start:end] = data['FACTS'][KPI_index[i]].strip()
    
    #if KPI start after the market seperation row
    if KPI_index[i]-1 in market_segment_index :
        data['KPI'][KPI_index[i]-1] = ''

number of non nan values: 136

index of not nan values:

 1                                         Ventes Volume
1538                                        Ventes Valeur
3075                                         Prix Moyen
4612                                        Prix Moyen UC
6149                                                   DN
                               ...
201355                                Ventes Valeur Promo
202892                                     Nb moy de Réfs
204429                               Linéaire moyen en cm
205966     Part d'offre vendante / Total sauces féculents
207503    Part linéaire vendante / Total sauces féculents
Name: FACTS, Length: 136, dtype: object

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  from ipykernel import kernelapp as app
C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [311]:
data[4612-2:4612+5] # verification au changmenet de MARKET

,MARKET_INITIAL,FACTS,NIELSEN_DESCRIPTION,EMBALLAGE,MARQUE,GAMME,FORMAT,RECETTES,COMPTE,STD/PROMO,...,KPI,CATEGORY,ORGANIC,WEIGHT,INITIAL_INDEX,EAN_promo,EAN13_num,SAME_PRODUCT,LONG_BRAND,WEIGHT_num
4610,NaN,NaN,SAUCES POUR FECULENTS TUB ZAPETTI BUITONI,TUB,ZAPETTI BUITONI,NaN,NaN,NaN,NaN,NaN,...,Prix Moyen,SAUCES POUR FECULENTS,* not found,0,4610,,0,NaN,ZAPETTI BUITONI,0
4611,NaN,NaN,POUR FECULENTS TUB ZAPETTI ZAPETTI BUITONI LEG...,TUB,ZAPETTI BUITONI,LEGUMES,PF,NATURE,1CT,STD,...,Prix Moyen,SAUCES POUR FECULENTS,NON BIO,150G,4611,,3021690021851,"ZAPETTI BUITONI, LEGUMES, NATURE, TUB,",ZAPETTI ZAPETTI BUITONI,150
4612,NaN,Prix Moyen UC,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,Prix Moyen UC,NaN,,0,4612,,0,NaN,None,0
4613,NaN,NaN,AUT SCE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,Prix Moyen UC,AUT SCE,* not found,0,4613,,0,NaN,,0
4614,NaN,NaN,AUT SCE AUT EMB,AUT EMB,NaN,NaN,NaN,NaN,NaN,NaN,...,Prix Moyen UC,AUT SCE,* not found,0,4614,,0,NaN,,0
4615,NaN,NaN,AUT SCE AUT EMB AUT MQ,AUT EMB,AUT MQ,NaN,NaN,NaN,NaN,NaN,...,Prix Moyen UC,AUT SCE,* not found,0,4615,,0,NaN,AUT MQ,0
4616,NaN,NaN,AUT EMB AUT FAB AUT MQ SCE CLAS PF CITRON VERT...,AUT EMB,AUT MQ,SCE CLAS,PF,CITRON VERT PIMENT DOUX,1CT,STD,...,Prix Moyen UC,AUT SCE,NON BIO,100G,4616,,3760052155536,"AUT MQ, SCE CLAS, CITRON VERT PIMENT DOUX, AUT...",AUT FAB AUT MQ,100

In [310]:
n=15371
data[n-2:n+5] # verification au changmenet de MARKET

,MARKET_INITIAL,FACTS,NIELSEN_DESCRIPTION,EMBALLAGE,MARQUE,GAMME,FORMAT,RECETTES,COMPTE,STD/PROMO,...,KPI,CATEGORY,ORGANIC,WEIGHT,INITIAL_INDEX,EAN_promo,EAN13_num,SAME_PRODUCT,LONG_BRAND,WEIGHT_num
15369,NaN,NaN,SAUCES POUR FECULENTS TUB ZAPETTI BUITONI,TUB,ZAPETTI BUITONI,NaN,NaN,NaN,NaN,NaN,...,Poids des Ventes Volume Promo,SAUCES POUR FECULENTS,* not found,0,15369,,0,NaN,ZAPETTI BUITONI,0
15370,NaN,NaN,POUR FECULENTS TUB ZAPETTI ZAPETTI BUITONI LEG...,TUB,ZAPETTI BUITONI,LEGUMES,PF,NATURE,1CT,STD,...,Poids des Ventes Volume Promo,SAUCES POUR FECULENTS,NON BIO,150G,15370,,3021690021851,"ZAPETTI BUITONI, LEGUMES, NATURE, TUB,",ZAPETTI ZAPETTI BUITONI,150
15371,NaN,Poids des Ventes Valeur Promo,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,Poids des Ventes Valeur Promo,NaN,,0,15371,,0,NaN,None,0
15372,NaN,NaN,AUT SCE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,Poids des Ventes Valeur Promo,AUT SCE,* not found,0,15372,,0,NaN,,0
15373,NaN,NaN,AUT SCE AUT EMB,AUT EMB,NaN,NaN,NaN,NaN,NaN,NaN,...,Poids des Ventes Valeur Promo,AUT SCE,* not found,0,15373,,0,NaN,,0
15374,NaN,NaN,AUT SCE AUT EMB AUT MQ,AUT EMB,AUT MQ,NaN,NaN,NaN,NaN,NaN,...,Poids des Ventes Valeur Promo,AUT SCE,* not found,0,15374,,0,NaN,AUT MQ,0
15375,NaN,NaN,AUT EMB AUT FAB AUT MQ SCE CLAS PF CITRON VERT...,AUT EMB,AUT MQ,SCE CLAS,PF,CITRON VERT PIMENT DOUX,1CT,STD,...,Poids des Ventes Valeur Promo,AUT SCE,NON BIO,100G,15375,,3760052155536,"AUT MQ, SCE CLAS, CITRON VERT PIMENT DOUX, AUT...",AUT FAB AUT MQ,100

In [309]:
data.tail()

,MARKET_INITIAL,FACTS,NIELSEN_DESCRIPTION,EMBALLAGE,MARQUE,GAMME,FORMAT,RECETTES,COMPTE,STD/PROMO,...,KPI,CATEGORY,ORGANIC,WEIGHT,INITIAL_INDEX,EAN_promo,EAN13_num,SAME_PRODUCT,LONG_BRAND,WEIGHT_num
209035,NaN,NaN,POUR FECULENTS TUB PANZANI SA PANZANI PESTO PF...,TUB,PANZANI,PESTO,PF,PESTO VERD,1CT,STD,...,Part linéaire vendante / Total sauces féculents,SAUCES POUR FECULENTS,NON BIO,160G,209035,,3038359005657,"PANZANI, PESTO, PESTO VERD, TUB,",PANZANI SA PANZANI,160
209036,NaN,NaN,SAUCES POUR FECULENTS TUB ZAKIA,TUB,ZAKIA,NaN,NaN,NaN,NaN,NaN,...,Part linéaire vendante / Total sauces féculents,SAUCES POUR FECULENTS,* not found,0,209036,,0,NaN,ZAKIA,0
209037,NaN,NaN,POUR FECULENTS TUB AUT FAB ZAKIA LEGUMES PF TO...,TUB,ZAKIA,LEGUMES,PF,TOMATE PIMENTE,1CT,STD,...,Part linéaire vendante / Total sauces féculents,SAUCES POUR FECULENTS,NON BIO,180G,209037,,3038359001413,"ZAKIA, LEGUMES, TOMATE PIMENTE, TUB,",AUT FAB ZAKIA,180
209038,NaN,NaN,SAUCES POUR FECULENTS TUB ZAPETTI BUITONI,TUB,ZAPETTI BUITONI,NaN,NaN,NaN,NaN,NaN,...,Part linéaire vendante / Total sauces féculents,SAUCES POUR FECULENTS,* not found,0,209038,,0,NaN,ZAPETTI BUITONI,0
209039,NaN,NaN,POUR FECULENTS TUB ZAPETTI ZAPETTI BUITONI LEG...,TUB,ZAPETTI BUITONI,LEGUMES,PF,NATURE,1CT,STD,...,Part linéaire vendante / Total sauces féculents,SAUCES POUR FECULENTS,NON BIO,150G,209039,,3021690021851,"ZAPETTI BUITONI, LEGUMES, NATURE, TUB,",ZAPETTI ZAPETTI BUITONI,150

In [308]:
#-------------------------------------------------------------------------------
#-------------------------------------------------------------------------------
# 3.3.FILL IN CATEGORY AT BEGINNING OF EACH KPI => CATEGORY

cat=''
#print('list of Nielsen Categories (items):\n')
for i in range(0,data.shape[0]):
    if pd.isnull(data['EMBALLAGE'][i]):
        cat=data['NIELSEN_DESCRIPTION'][i]
        data['CATEGORY'][i]=cat
        #print(cat)
    else:
        data['CATEGORY'][i]=cat

data.head(200)

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  # Remove the CWD from sys.path while we load stuff.
C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  del sys.path[0]

,MARKET_INITIAL,FACTS,NIELSEN_DESCRIPTION,EMBALLAGE,MARQUE,GAMME,FORMAT,RECETTES,COMPTE,STD/PROMO,...,KPI,CATEGORY,ORGANIC,WEIGHT,INITIAL_INDEX,EAN_promo,EAN13_num,SAME_PRODUCT,LONG_BRAND,WEIGHT_num
0,HMSM + PROXI + DRIVE + SDMP,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,,NaN,,0,0,,0,NaN,None,0
1,NaN,Ventes Volume,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,Ventes Volume,NaN,,0,1,,0,NaN,None,0
2,NaN,NaN,AUT SCE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,Ventes Volume,AUT SCE,* not found,0,2,,0,NaN,,0
3,NaN,NaN,AUT SCE AUT EMB,AUT EMB,NaN,NaN,NaN,NaN,NaN,NaN,...,Ventes Volume,AUT SCE,* not found,0,3,,0,NaN,,0
4,NaN,NaN,AUT SCE AUT EMB AUT MQ,AUT EMB,AUT MQ,NaN,NaN,NaN,NaN,NaN,...,Ventes Volume,AUT SCE,* not found,0,4,,0,NaN,AUT MQ,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
195,NaN,NaN,SAUCES POUR FECULENTS BRIC PANZANI,BRIC,PANZANI,NaN,NaN,NaN,NaN,NaN,...,Ventes Volume,SAUCES POUR FECULENTS,* not found,0,195,,0,NaN,PANZANI,0
196,NaN,NaN,FECULENTS BRIC PANZANI SA PANZANI LEGUMES MF O...,BRIC,PANZANI,LEGUMES,MF,OIGNONS ET AIL,1CT,STD,...,Ventes Volume,SAUCES POUR FECULENTS,NON BIO,500G,196,,3038359004186,"PANZANI, LEGUMES, OIGNONS ET AIL, BRIC,",PANZANI SA PANZANI,500
197,NaN,NaN,SAUCES POUR FECULENTS BRIC ZAPETTI BUITONI,BRIC,ZAPETTI BUITONI,NaN,NaN,NaN,NaN,NaN,...,Ventes Volume,SAUCES POUR FECULENTS,* not found,0,197,,0,NaN,ZAPETTI BUITONI,0
198,NaN,NaN,BRIC ZAPETTI ZAPETTI BUITONI BOLO CLASSIQUE MF...,BRIC,ZAPETTI BUITONI,BOLO CLASSIQUE,MF,BOLOGNAISE,1CT,STD,...,Ventes Volume,SAUCES POUR FECULENTS,NON BIO,350G,198,,3021690020298,"ZAPETTI BUITONI, BOLO CLASSIQUE, BOLOGNAISE, B...",ZAPETTI ZAPETTI BUITONI,350
199,NaN,NaN,FECULENTS BRIC ZAPETTI ZAPETTI BUITONI LEGUMES...,BRIC,ZAPETTI BUITONI,LEGUMES,MF,AIL OIGNON,3CT,STD,...,Ventes Volume,SAUCES POUR FECULENTS,NON BIO,400G,199,,3021690024715,"ZAPETTI BUITONI, LEGUMES, AIL OIGNON, BRIC,",ZAPETTI ZAPETTI BUITONI,400

In [281]:

############################################################
#     4. PROCESSING NIELSEN DESCRIPTION                    #
############################################################

In [282]:
#-------------------------------------------------------------------------------
#-------------------------------------------------------------------------------
#     4.1 EXTRACTING LONG BRAND

In [283]:
temp_N_desc_short = np.array(data['NIELSEN_DESCRIPTION'])
temp_N_gamme = np.array(data['GAMME'])
temp = list(zip(temp_N_desc_short, temp_N_gamme))
result1 = list(map(split_item_left, temp))

temp_N_desc_short_emb = np.array(data['EMBALLAGE'])
temp2 = list(zip(result1, temp_N_desc_short_emb))

result2 = list(map(split_item_right, temp2))

data['LONG_BRAND'] = result2
data['LONG_BRAND']=data['LONG_BRAND'].str.strip()

In [284]:
terms_to_be_removed = ['SAUCES POUR FECULENTS ', 'AUT SCE','POUR FECULENTS ',] 

for term in terms_to_be_removed :
    data['LONG_BRAND'] = data['LONG_BRAND'].str.replace(term, '', regex=True, case=False)

In [285]:
sorted(unique_clean(data,'LONG_BRAND'))

number of  LONG_BRAND  unique (non null) values:  56
<class 'list'>

['AUT FAB AUT MQ',
 'AUT FAB BJORG',
 'AUT FAB CASERTA',
 'AUT FAB DE CECCO',
 'AUT FAB FLORELLI',
 'AUT FAB ITALIANS DO IT BETTER',
 'AUT FAB JARDIN',
 'AUT FAB JARDIN BIO',
 'AUT FAB LE CABANON',
 'AUT FAB LOUIS MARTIN',
 'AUT FAB LUCIEN GEORGELIN',
 'AUT FAB MQ FAB 1 PRX',
 'AUT FAB OLD EL PASO',
 'AUT FAB POLLI',
 'AUT FAB RUMMO',
 'AUT FAB SOLEILLANS',
 'AUT FAB ZAKIA',
 'AUT MQ',
 'BARILLA',
 'BJORG',
 'BUITONI',
 'CASERTA',
 'CIRIO',
 'CREAZIONI ITALI',
 'DE CECCO',
 'FLORELLI',
 'HEINZ',
 'ITALIANS DO IT BETTER',
 'JARDIN BIO',
 'KNORR',
 'LE CABANON',
 'LOUIS MARTIN',
 'LUCIEN GEORGELIN',
 'MASTER F SUZY WAN',
 'MASTER F UNC BENS',
 'MDD',
 'MDD 1 PRX',
 'MQ FAB 1 PRX',
 'MUTTI',
 'OLD EL PASO',
 'PANZANI',
 'PANZANI SA PANZANI',
 'PASTACORP RIVOIRE & CARRET',
 'POLLI',
 'RIVOIRE & CARRET',
 'RUMMO',
 'SACLA',
 'SAUCES POUR FECULENTS',
 'SOLEILLANS',
 'SUZY WAN',
 'UBF KNORR',
 'UNC BENS',
 'VICTORIA',
 'ZAKIA',
 'ZAPETTI BUITONI',
 'ZAPETTI ZAPETTI BUITONI']

In [286]:
# =>  LONG_BRAND IS NOT CONSISTENT
# FOR EXAMPLE 
# 'ZAKIA' // 'AUT FAB ZAKIA'
# 'ITALIANS DO IT BETTER'//'AUT FAB ITALIANS DO IT BETTER',
# 'PANZANI' //  'PANZANI SA PANZANI',
# 'ZAPETTI BUITONI' // 'ZAPETTI ZAPETTI BUITONI' // 'BUITONI',

In [287]:
# IDENTIFY MDD IN BRANDS AND TAG LINES IN EAN13 
# (NIELSEN DB ONLY CONTAINS SUB TOTAL FOR MDD PRODUCTS)
# EAN13 FOR MDD PRODUCTS ARE NOT AVAILABLE IN NIELSEN DB

In [288]:
text_in_df(data,'MARQUE', 'MDD$')
#1224 = 136* 9 = only in 9 références !!!! :S
# 136 = 8 MARKETS x 17 KPI

text " MDD$ appears 1224 lines, in 1 different values

     0
0  MDD

In [289]:
#df_with_text(data,'MARQUE','MDD$').tail(20)get_

In [290]:
text_in_df(data,'MARQUE','MDD 1 PRX')
#272 = 136 * 2 = only in 2 références !!!! :S
# 136 = 8 MARKETS x 17 KPI

text " MDD 1 PRX appears 272 lines, in 1 different values

           0
0  MDD 1 PRX

In [291]:
#df_with_text(data,'MARQUE','MDD 1 PRX')

In [292]:
#-------------------------------------------------------------------------------
#-------------------------------------------------------------------------------
#  4.2. EXTRACT ORGANIC PRODUCTS (BIO) FROM NIELSEN DESCRIPTION   #
#  (BIO / NON BIO)                                                #

In [293]:
# ABC LAMBDA FUNCTION TO SPLIT ON '*'
#data['ORGANIC'] = data['NIELSEN_DESCRIPTION']+'*'
#data['ORGANIC'] = data['NIELSEN_DESCRIPTION'].apply(lambda desc: desc.split('*')[1:])
#data['ORGANIC'] = data['NIELSEN_DESCRIPTION'].str.replace(data['ORGANIC'],'')
#print(data['ORGANIC'])

In [122]:
def split_star_left(col) :
    if isinstance(col, str) :
        return col.split('*', 1)[0] # keep first part [0] of split (before the splitter (st[1])
    else :
        return ''

def split_star_right(col) :
    if isinstance(col, str) :
        split = col.split('*', 2)
        if len(split)>2:
            return split[2]  # keep second part [1] of split (after the splitter (st[1])
        elif len(split)>1:
            return split[1]  # keep second part [1] of split (after the splitter (st[1])
        else:
            return 'STAR not found'
    else :
        return ''

In [120]:
def bio_non_bio(col) :
    if isinstance(col, str) :
        if col[-7:]=='NON BIO':
            return ' NON BIO'
        elif (col[-3:]=='BIO')&(col[-7:]!='NON BIO'):
            return ' BIO'
        else:
            return 'separator'
    else :
        return ''
    print(n)

In [131]:
#INITAL DEFINITION  WITH STAR (PB 28560 products not identified !!!!!
data['ORGANIC'] = list(map(split_star_right, data['NIELSEN_DESCRIPTION']))

print(set(data['ORGANIC']),'\n')
print(data[['ORGANIC','EAN13','MARQUE']].groupby(by='ORGANIC').count())
temp=data[data['ORGANIC']=='STAR not found']
print('\nnumber of EAN13 products not recognised:',len(temp['EAN13'].unique()))

{'', 'STAR not found', ' NON BIO', ' BIO'}

                 EAN13  MARQUE
ORGANIC
                   144       0
 BIO             23936   23936
 NON BIO        156400  156400
STAR not found   28560   26112

number of EAN13 products not recognised: 107

In [133]:
# ORGANIC DEFINITION BASED ON 'BIO' and 'NON BIO'
data['ORGANIC'] = list(map(bio_non_bio, data['NIELSEN_DESCRIPTION']))

print(set(data['ORGANIC']))
print(data[['ORGANIC','EAN13','MARQUE']].groupby(by='ORGANIC').count())
temp=data[data['ORGANIC']=='unknown']
print('\nnumber of EAN13 products not recognised:',len(temp['EAN13'].unique()))

{'', ' NON BIO', ' BIO', 'separator'}
            EAN13  MARQUE
ORGANIC
              144       0
 BIO        25296   25296
 NON BIO   170000  170000
separator   13600   11152

number of EAN13 products not recognised: 0

In [296]:
#-------------------------------------------------------------------------------
#-------------------------------------------------------------------------------
#     4.3. PROCESSING WEIGHT                                        #
#     (STRING / NON STRING)                                       #

In [150]:
#-------------------------------------------------------------------------------
# EXTRACT WEIGHT (STRING) FROM NIELSEN_DESCRIPTION

import re

# s is the search to execute (compile)
 

def find_weight(text):
    s = re.compile('\d+G')
    if isinstance(text,str):
        weights=s.findall(text)
        if len(weights) >0:
            return weights[-1]
    
data['WEIGHT']=data['NIELSEN_DESCRIPTION'].apply(lambda row: find_weight(row))

In [154]:
WEIGHT_U=data['WEIGHT'].unique()
print('number of different weights in database:',len(WEIGHT_U))
WEIGHT_U

number of different weights in database: 85

array([None, '100G', '300G', '200G', '50G', '375G', '150G', '135G',
       '250G', '435G', '270G', '95G', '80G', '500G', '310G', '350G',
       '325G', '420G', '340G', '180G', '190G', '235G', '280G', '130G',
       '185G', '240G', '175G', '227G', '120G', '290G', '195G', '400G',
       '215G', '520G', '210G', '410G', '155G', '110G', '2000G', '4200G',
       '2800G', '380G', '385G', '40G', '90G', '1000G', '320G', '425G',
       '265G', '330G', '170G', '355G', '370G', '295G', '285G', '680G',
       '650G', '600G', '700G', '560G', '530G', '780G', '660G', '580G',
       '360G', '440G', '305G', '460G', '390G', '220G', '212G', '260G',
       '125G', '140G', '160G', '166G', '690G', '490G', '510G', '345G',
       '415G', '312G', '226G', '800G', '470G'], dtype=object)

In [184]:
#-------------------------------------------------------------------------------
# EXTRACT WEIGHT AS INTEGER FROM WIEGHT (string)

def remove_G_in_weight(text):
    if isinstance(text,str):
        return text[:-1]
    else:
        return '0'
   
data['WEIGHT_num']=data['WEIGHT'].apply(lambda row: remove_G_in_weight(row)).astype(int)
print(sorted(data['WEIGHT_num'].unique()))

#!!!!!!!!!!!!!!  0 = UNKOWN !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

[0, 40, 50, 80, 90, 95, 100, 110, 120, 125, 130, 135, 140, 150, 155, 160, 166, 170, 175, 180, 185, 190, 195, 200, 210, 212, 215, 220, 226, 227, 235, 240, 250, 260, 265, 270, 280, 285, 290, 295, 300, 305, 310, 312, 320, 325, 330, 340, 345, 350, 355, 360, 370, 375, 380, 385, 390, 400, 410, 415, 420, 425, 435, 440, 460, 470, 490, 500, 510, 520, 530, 560, 580, 600, 650, 660, 680, 690, 700, 780, 800, 1000, 2000, 2800, 4200]

In [ ]:
###############################################################
#                                                             #
#   5. CREATE column SAME_PRODUCT                             #
#                                                             #
###############################################################

In [185]:
#-------------------------------------------------------------------------------
#-------------------------------------------------------------------------------
# 2.6 CREATION OF COLUMN "SAME_PRODUCT" = MARQUE, EMBALLAGE, GAMME, RECETTES, ORGANIC
# will be used to approximate similar EAN13 in OPENFF mongo DB

data['SAME_PRODUCT'] = \
    data['MARQUE'] + ', ' + \
    data['GAMME'] + ', '  + \
    data['RECETTES'] + ', '  + \
    data['EMBALLAGE'] + ', ' + \
    data['ORGANIC'].astype(str)
    # + ', '  + data['WEIGHT'].astype(str)

In [186]:
data['SAME_PRODUCT'].head(10)

0                                                  NaN
1                                                  NaN
2                                                  NaN
3                                                  NaN
4                                                  NaN
5    AUT MQ, SCE CLAS, CITRON VERT PIMENT DOUX, AUT...
6    AUT MQ, SCE CLAS, CURRY JAUNE THAI, AUT EMB,  ...
7    AUT MQ, SCE CLAS, CURRY VERT & LEGUMES, AUT EM...
8            AUT MQ, SCE CLAS, YUZU, AUT EMB,  NON BIO
9                                                  NaN
Name: SAME_PRODUCT, dtype: object

In [301]:
###############################################################
#                                                             #
#   6. SAVE PREPROCESSED NIELSEN DATA (ALL ROWS STILL IN DB)  #
#                                                             #
###############################################################

In [7]:
%pwd

'C:\\Users\\baudant\\OneDrive - BEFIVE\\italians_do_it_better\\N_NIELSEN'

In [187]:
#data.drop(['N_DESC_SHORT'],axis=1,inplace=True)
#data.rename(columns={'MARKET': 'MARKET_INITIAL'},inplace=True)
#data.rename(columns={'MKT_SEGMENT_INITIAL': 'MARKET'},inplace=True)
data.columns

Index(['MARKET_INITIAL', 'FACTS', 'NIELSEN_DESCRIPTION', 'EMBALLAGE', 'MARQUE',
       'GAMME', 'FORMAT', 'RECETTES', 'COMPTE', 'STD/PROMO', 'ITEM',
       'CAM AN-1', 'DERNIER CAM', '4 S 28/01/18', '4 S 25/02/18',
       '4 S 25/03/18', '4 S 22/04/18', '4 S 20/05/18', '4 S 17/06/18',
       '4 S 15/07/18', '4 S 12/08/18', '4 S 09/09/18', '4 S 07/10/18',
       '4 S 04/11/18', '4 S 02/12/18', '4 S 30/12/18', '4 S 27/01/19',
       '4 S 24/02/19', '4 S 24/03/19', '4 S 21/04/19', '4 S 19/05/19',
       '4 S 16/06/19', '4 S 14/07/19', '4 S 11/08/19', '4 S 08/09/19',
       '4 S 06/10/19', '4 S 03/11/19', '4 S 01/12/19', '4 S 29/12/19', 'EAN13',
       'MARKET', 'KPI', 'CATEGORY', 'ORGANIC', 'WEIGHT', 'INITIAL_INDEX',
       'EAN_promo', 'EAN13_num', 'SAME_PRODUCT', 'LONG_BRAND', 'WEIGHT_num'],
      dtype='object')

In [188]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 209040 entries, 0 to 209039
Data columns (total 51 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   MARKET_INITIAL       8 non-null       object
 1   FACTS                136 non-null     object
 2   NIELSEN_DESCRIPTION  208896 non-null  object
 3   EMBALLAGE            208624 non-null  object
 4   MARQUE               206448 non-null  object
 5   GAMME                194752 non-null  object
 6   FORMAT               194752 non-null  object
 7   RECETTES             194752 non-null  object
 8   COMPTE               194752 non-null  object
 9   STD/PROMO            194752 non-null  object
 10  ITEM                 194752 non-null  object
 11  CAM AN-1             208896 non-null  float64
 12  DERNIER CAM          208896 non-null  float64
 13  4 S 28/01/18         208896 non-null  float64
 14  4 S 25/02/18         208896 non-null  float64
 15  4 S 25/03/18         208896 non-null  float64
 16  4 S 22/04/18         208896 non-null  float64
 17  4 S 20/05/18         208896 non-null  float64
 18  4 S 17/06/18         208896 non-null  float64
 19  4 S 15/07/18         208896 non-null  float64
 20  4 S 12/08/18         208896 non-null  float64
 21  4 S 09/09/18         208896 non-null  float64
 22  4 S 07/10/18         208896 non-null  float64
 23  4 S 04/11/18         208896 non-null  float64
 24  4 S 02/12/18         208896 non-null  float64
 25  4 S 30/12/18         208896 non-null  float64
 26  4 S 27/01/19         208896 non-null  float64
 27  4 S 24/02/19         208896 non-null  float64
 28  4 S 24/03/19         208896 non-null  float64
 29  4 S 21/04/19         208896 non-null  float64
 30  4 S 19/05/19         208896 non-null  float64
 31  4 S 16/06/19         208896 non-null  float64
 32  4 S 14/07/19         208896 non-null  float64
 33  4 S 11/08/19         208896 non-null  float64
 34  4 S 08/09/19         208896 non-null  float64
 35  4 S 06/10/19         208896 non-null  float64
 36  4 S 03/11/19         208896 non-null  float64
 37  4 S 01/12/19         208896 non-null  float64
 38  4 S 29/12/19         208896 non-null  float64
 39  EAN13                209040 non-null  object
 40  MARKET               209040 non-null  object
 41  KPI                  209032 non-null  object
 42  CATEGORY             208896 non-null  object
 43  ORGANIC              209040 non-null  object
 44  WEIGHT               194616 non-null  object
 45  INITIAL_INDEX        209040 non-null  int64
 46  EAN_promo            2040 non-null    object
 47  EAN13_num            209040 non-null  int64
 48  SAME_PRODUCT         194752 non-null  object
 49  LONG_BRAND           198560 non-null  object
 50  WEIGHT_num           209040 non-null  int32
dtypes: float64(28), int32(1), int64(2), object(20)
memory usage: 92.1+ MB

In [191]:
data.head(10)

,MARKET_INITIAL,FACTS,NIELSEN_DESCRIPTION,EMBALLAGE,MARQUE,GAMME,FORMAT,RECETTES,COMPTE,STD/PROMO,...,KPI,CATEGORY,ORGANIC,WEIGHT,INITIAL_INDEX,EAN_promo,EAN13_num,SAME_PRODUCT,LONG_BRAND,WEIGHT_num
0,HMSM + PROXI + DRIVE + SDMP,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,,None,0,NaN,0,NaN,NaN,0
1,NaN,Ventes Volume,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,Ventes Volume,NaN,,None,1,NaN,0,NaN,NaN,0
2,NaN,NaN,AUT SCE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,Ventes Volume,AUT SCE,separator,None,2,NaN,0,NaN,NaN,0
3,NaN,NaN,AUT SCE AUT EMB,AUT EMB,NaN,NaN,NaN,NaN,NaN,NaN,...,Ventes Volume,AUT SCE,separator,None,3,NaN,0,NaN,NaN,0
4,NaN,NaN,AUT SCE AUT EMB AUT MQ,AUT EMB,AUT MQ,NaN,NaN,NaN,NaN,NaN,...,Ventes Volume,AUT SCE,separator,None,4,NaN,0,NaN,AUT MQ,0
5,NaN,NaN,AUT EMB AUT FAB AUT MQ SCE CLAS PF CITRON VERT...,AUT EMB,AUT MQ,SCE CLAS,PF,CITRON VERT PIMENT DOUX,1CT,STD,...,Ventes Volume,AUT SCE,NON BIO,100G,5,NaN,3760052155536,"AUT MQ, SCE CLAS, CITRON VERT PIMENT DOUX, AUT...",AUT FAB AUT MQ,100
6,NaN,NaN,AUT SCE AUT EMB AUT FAB AUT MQ SCE CLAS PF CUR...,AUT EMB,AUT MQ,SCE CLAS,PF,CURRY JAUNE THAI,1CT,STD,...,Ventes Volume,AUT SCE,NON BIO,300G,6,NaN,8854404005213,"AUT MQ, SCE CLAS, CURRY JAUNE THAI, AUT EMB, ...",AUT FAB AUT MQ,300
7,NaN,NaN,SCE AUT EMB AUT FAB AUT MQ SCE CLAS PF CURRY V...,AUT EMB,AUT MQ,SCE CLAS,PF,CURRY VERT & LEGUMES,1CT,STD,...,Ventes Volume,AUT SCE,NON BIO,300G,7,NaN,8858135071028,"AUT MQ, SCE CLAS, CURRY VERT & LEGUMES, AUT EM...",AUT FAB AUT MQ,300
8,NaN,NaN,AUT SCE AUT EMB AUT FAB AUT MQ SCE CLAS PF YUZ...,AUT EMB,AUT MQ,SCE CLAS,PF,YUZU,1CT,STD,...,Ventes Volume,AUT SCE,NON BIO,100G,8,NaN,3760052155512,"AUT MQ, SCE CLAS, YUZU, AUT EMB, NON BIO",AUT FAB AUT MQ,100
9,NaN,NaN,AUT SCE BRIC,BRIC,NaN,NaN,NaN,NaN,NaN,NaN,...,Ventes Volume,AUT SCE,separator,None,9,NaN,0,NaN,NaN,0

In [11]:
%pwd

'C:\\Users\\baudant\\OneDrive - BEFIVE\\italians_do_it_better\\N_NIELSEN'

In [192]:
#SAVE PREPROCESSDED DATA
data.to_csv('output_data/N_ALL_DATA_preprocessed.csv')

In [1]:
#RELOAD PREPROCESSDED DATA
import pandas as pd
data=pd.read_csv('output_data/N_ALL_DATA_preprocessed.csv',index_col=0)
data['EAN13']=data['EAN13'].astype(str)
data.head()

C:\ProgramData\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3063: DtypeWarning: Columns (1) have mixed types.Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

,MARKET_INITIAL,FACTS,NIELSEN_DESCRIPTION,EMBALLAGE,MARQUE,GAMME,FORMAT,RECETTES,COMPTE,STD/PROMO,...,KPI,CATEGORY,ORGANIC,WEIGHT,INITIAL_INDEX,EAN_promo,EAN13_num,SAME_PRODUCT,LONG_BRAND,WEIGHT_num
0,HMSM + PROXI + DRIVE + SDMP,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,0,0,NaN,0,NaN,NaN,0
1,NaN,Ventes Volume,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,Ventes Volume,NaN,NaN,0,1,NaN,0,NaN,NaN,0
2,NaN,NaN,AUT SCE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,Ventes Volume,AUT SCE,* not found,0,2,NaN,0,NaN,NaN,0
3,NaN,NaN,AUT SCE AUT EMB,AUT EMB,NaN,NaN,NaN,NaN,NaN,NaN,...,Ventes Volume,AUT SCE,* not found,0,3,NaN,0,NaN,NaN,0
4,NaN,NaN,AUT SCE AUT EMB AUT MQ,AUT EMB,AUT MQ,NaN,NaN,NaN,NaN,NaN,...,Ventes Volume,AUT SCE,* not found,0,4,NaN,0,NaN,AUT MQ,0