In [1]:
import pandas as pd
import numpy as np

In [2]:
#################################################
# 0) FUNCTIONS                                  #
#################################################

In [3]:
import sys
sys.path.append('../')
from func import *

#DEFINED FUNCTIONS :
    
#unique_clean(data,col,pr=0)

#df_with_text(data,col,text)
#text_in_df(data,col,text)
#two_text_in_df(data,col,text1,text2)
#two_text_in_df(data,col,text1,text2='')

#values_U_not_nan(data,col_name)
#not_nan_get_values(data,col_name,pr=0)
#not_nan_get_index(data, col_name, pr=0)
#nan_get_index(data, col_name, pr=0)

#is_not_decimal(a)
#is_not_13(a)
#split_text_left(text_to_split,text)
#split_item_left(st)
#split_item_right(st)

#find_weight(text):     #s = re.compile('\d+G') extracts '210G'

In [4]:

##########################################
# 1) IMPORT DATA
##########################################

In [5]:

####################################################################################
# 1.1) IMPORT M_PROD_MFINAL (merge Nielsen and Openfood facts)

prod = pd.read_csv('../M_MERGE/output_data/M_PROD_FINAL.csv',index_col=0)
prod['O_EAN13'] = prod['O_EAN13'].astype(str)
prod['N_EAN13'] = prod['N_EAN13'].astype(str)
prod['O_EAN13']=prod['O_EAN13'].apply(lambda row : row[0:-2])
prod['N_EAN13']=prod['N_EAN13'].apply(lambda row : row[0:-2])
print('-'*50,'\nPRODUCTS\n','-'*50)
print('\nproduct shape:',prod.shape,'\n')
print('\n',prod.info())

--------------------------------------------------
PRODUCTS
 --------------------------------------------------

product shape: (3979, 74)

<class 'pandas.core.frame.DataFrame'>
Int64Index: 3979 entries, 0 to 3978
Data columns (total 74 columns):
 #   Column                                                   Non-Null Count  Dtype
---  ------                                                   --------------  -----
 0   O_EAN13                                                  3979 non-null   object
 1   O_product_name_fr                                        3305 non-null   object
 2   O_product_name                                           3419 non-null   object
 3   O_brands                                                 3434 non-null   object
 4   O_brands_tags_str                                        3434 non-null   object
 5   O_brands_tags                                            3434 non-null   object
 6   O_serving_size                                           539 non-null    object
 7   O_serving_quantity                                       539 non-null    float64
 8   O_countries_hierarchy                                    3434 non-null   object
 9   O_cities_tags                                            2460 non-null   object
 10  O_manufacturing_places                                   753 non-null    object
 11  O_purchase_places                                        1170 non-null   object
 12  O_countries_tags                                         3434 non-null   object
 13  O_categories                                             2995 non-null   object
 14  O_category_properties                                    3434 non-null   object
 15  O_pnns_groups_1                                          3433 non-null   object
 16  O_pnns_groups_2                                          3434 non-null   object
 17  O_compared_to_category                                   2970 non-null   object
 18  O_interface_version_modified                             3430 non-null   object
 19  O_ingredients_n                                          2542 non-null   float64
 20  O_ingredients_text                                       2542 non-null   object
 21  O_ingredients                                            3267 non-null   object
 22  O_salt_content                                           3267 non-null   object
 23  O_max_salt_content                                       3434 non-null   float64
 24  O_min_salt_content                                       3434 non-null   float64
 25  O_oil_content                                            3267 non-null   object
 26  O_max_oil_content                                        3434 non-null   float64
 27  O_min_oil_content                                        3434 non-null   float64
 28  O_oil_type                                               948 non-null    object
 29  O_nutriments                                             3434 non-null   object
 30  O_energy_100g                                            3309 non-null   float64
 31  O_energy_kcal_100g                                       2691 non-null   float64
 32  O_saturated_fat_100g                                     3280 non-null   float64
 33  O_fat_100g                                               3291 non-null   float64
 34  O_carbohydrates_100g                                     3293 non-null   float64
 35  O_sugars_100g                                            3286 non-null   float64
 36  O_fruits_vegetables_nuts_estimate_from_ingredients_100g  2541 non-null   float64
 37  O_proteins_100g                                          3307 non-null   float64
 38  O_sodium_100g                                            3281 non-null   float64
 39  O_salt_100g                                              3281 non-null   float64
 40  O_nutrition_score_fr_100g                                2816 non-null   float64
 41  O_fiber_100g                                             1557 non-null   float64
 42  O_nova_group_100g                                        2320 non-null   float64
 43  O_COUNT                                                  3434 non-null   float64
 44  O_date_modified                                          3430 non-null   float64
 45  O_BRANDS_UPPER                                           3434 non-null   object
 46  S_brands                                                 1975 non-null   object
 47  S_BRAND                                                  1975 non-null   object
 48  S_BRAND_TYPE                                             1975 non-null   object
 49  S_BRANDS_UPPER                                           1975 non-null   object
 50  Unnamed: 0.1                                             1443 non-null   float64
 51  index                                                    1443 non-null   float64
 52  N_EAN13                                                  3979 non-null   object
 53  N_MARQUE                                                 1443 non-null   object
 54  N_SAME_PRODUCT                                           1443 non-null   object
 55  N_GAMME                                                  1432 non-null   object
 56  N_RECETTES                                               1432 non-null   object
 57  N_ORGANIC                                                1443 non-null   object
 58  N_FORMAT                                                 1432 non-null   object
 59  N_WEIGHT_num                                             1443 non-null   float64
 60  N_EMBALLAGE                                              1443 non-null   object
 61  N_COMPTE                                                 1432 non-null   object
 62  N_STD/PROMO                                              1432 non-null   object
 63  N_Ventes_Valeur_2019                                     1443 non-null   float64
 64  N_Ventes_Valeur_2018                                     1443 non-null   float64
 65  N_ITEM                                                   1432 non-null   object
 66  N_NIELSEN_DESCRIPTION                                    1443 non-null   object
 67  N_INITIAL_INDEX                                          1443 non-null   float64
 68  N_CATEGORY                                               1443 non-null   object
 69  N_COUNT                                                  1443 non-null   float64
 70  I_ITEM                                                   1272 non-null   object
 71  I_CATEGORY                                               1112 non-null   object
 72  I_Ventes_Volume_2018                                     1443 non-null   float64
 73  I_Ventes_Volume_2019                                     1443 non-null   float64
dtypes: float64(30), object(44)
memory usage: 2.3+ MB

 None

In [6]:
prod.describe()

,O_serving_quantity,O_ingredients_n,O_max_salt_content,O_min_salt_content,O_max_oil_content,O_min_oil_content,O_energy_100g,O_energy_kcal_100g,O_saturated_fat_100g,O_fat_100g,...,O_date_modified,Unnamed: 0.1,index,N_WEIGHT_num,N_Ventes_Valeur_2019,N_Ventes_Valeur_2018,N_INITIAL_INDEX,N_COUNT,I_Ventes_Volume_2018,I_Ventes_Volume_2019
count,539.000000,2542.000000,3434.000000,3434.000000,3434.000000,3434.000000,3309.000000,2691.000000,3280.000000,3291.000000,...,3.430000e+03,1443.000000,1443.000000,1443.000000,1.443000e+03,1.443000e+03,1443.000000,1443.0,1.443000e+03,1.443000e+03
mean,104.684694,15.557828,5.332231,0.208992,6.201473,1.573271,839.675219,203.408162,3.487313,15.359863,...,2.014798e+07,721.000000,2319.543313,281.002772,2.382602e+05,2.293434e+05,2319.543313,1.0,2.066464e+04,1.992479e+04
std,103.746530,10.924430,10.745475,1.346590,16.430884,6.070739,656.277295,160.898485,5.282617,17.616821,...,1.644127e+04,416.702532,434.142128,191.472533,2.579302e+06,2.415907e+06,434.142128,0.0,1.000366e+05,9.850900e+04
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,2.012062e+07,0.000000,1542.000000,0.000000,0.000000e+00,0.000000e+00,1542.000000,1.0,0.000000e+00,0.000000e+00
25%,28.125000,9.000000,0.000000,0.000000,0.000000,0.000000,339.000000,82.000000,0.300000,2.100000,...,2.015032e+07,360.500000,1958.500000,190.000000,2.140000e+01,1.130000e+01,1958.500000,1.0,0.000000e+00,0.000000e+00
50%,78.000000,14.000000,0.000000,0.000000,0.000000,0.000000,582.000000,142.000000,1.600000,7.000000,...,2.015032e+07,721.000000,2319.000000,240.000000,4.451900e+03,2.857000e+03,2319.000000,1.0,7.390000e+01,9.310000e+01
75%,110.000000,19.000000,5.385950,0.000000,1.921429,0.000000,1259.000000,305.000000,4.100000,25.100000,...,2.015032e+07,1081.500000,2695.500000,350.000000,3.511795e+04,3.483705e+04,2695.500000,1.0,1.644000e+03,1.796900e+03
max,440.000000,131.000000,100.000000,50.000000,100.000000,90.000000,3766.000000,1772.000000,52.000000,100.000000,...,2.019083e+07,1442.000000,3074.000000,4200.000000,9.437020e+07,8.801080e+07,3074.000000,1.0,1.619278e+06,1.198247e+06

In [108]:
O_EAN13_U = unique_clean(prod,'O_EAN13')

print(O_EAN13_U[0])
type(O_EAN13_U[0])

number of  O_EAN13  unique (non null) values:  3431
<class 'list'>

87157215

str

In [109]:
####################################################################################
# 1.2) IMPORT INGREDIENTS (extracted form products in M_PROD_MFINAL)

ing = pd.read_csv('../O_OPENFF/output_data/O_INGREDIENTS_preprocessed.csv', index_col=0)
ing['O_EAN13'] = ing['O_EAN13'].astype(str)
print('-'*50,'\nINGREDIENTS\n','-'*50)
print('\ningredient shape:',ing.shape,'\n')
print('\n',ing.info())

--------------------------------------------------
INGREDIENTS
 --------------------------------------------------

ingredient shape: (39114, 18)

<class 'pandas.core.frame.DataFrame'>
Int64Index: 39114 entries, 0 to 39113
Data columns (total 18 columns):
O_EAN13                 39114 non-null object
id_ingredient           39114 non-null object
has_sub_ingredients     5631 non-null object
sub_ingredients         4888 non-null object
text                    39114 non-null object
percent_min             28684 non-null float64
percent_max             28684 non-null float64
percent                 6188 non-null float64
rank                    27771 non-null float64
product_name_fr         38105 non-null object
unknown_ingredient      39114 non-null int64
id_language             39114 non-null object
id_ing_sub_ing          4888 non-null object
sub_ing_dict            4775 non-null object
sub_ingredients_id      4770 non-null object
sub_ingredients_fr      0 non-null float64
sub_ingredients_text    4768 non-null object
ing_id_sub_ing_id       39114 non-null object
dtypes: float64(5), int64(1), object(12)
memory usage: 5.7+ MB

 None

In [110]:
# load marine file
tomato = pd.read_excel('../I_ITALIANS/Ingredient_analyse tomates.xlsx')
for col in tomato.columns :
    tomato.rename(columns={col : col.strip()}, inplace=True)

tomato['NORMALISED']=tomato['NORMALISED'].str.strip()

tomato=tomato[~tomato['NORMALISED'].isna()]
tomato=tomato[tomato['NORMALISED']!='other']
tomato=tomato[['id_ingredient','NORMALISED','SCORE']]

#filt = (~tomato['SCORE'].isna()) & (tomato['SCORE'] != 'Na')

#tomato['SCORE'][filt].astype(float)
tomato.shape

(168, 3)

In [111]:
tomato.sort_values(by='SCORE', ascending=False).head(20)

                                         id_ingredient NORMALISED  SCORE
304                              fr:Tomates italiennes     tomato    9.0
300  fr:Tomates cultivées dans le pays Marmandais e...     tomato    9.0
31                             fr:tomates Cœur de Bœuf     tomato    8.0
50                                   en:organic-tomato     tomato    8.0
26                                   en:fresh-tomatoes     tomato    8.0
297                            fr:Tomates Cœur de Bœuf     tomato    8.0
53                           fr:tomates pelées en cube     tomato    7.0
305                        fr:Tomates passées au tamis     tomato    7.0
7                                      en:tomato-cubes     tomato    7.0
112                                   fr:tomates cubes     tomato    7.0
70             fr:dés de toma- d' Concentré de tomates     tomato    7.0
121                                 fr:tomates en cube     tomato    7.0
261  fr:Pulpe de tomates fraîches avec morceaux et ...     tomato    6.0
262  fr:Pulpe de tomates fraîches avec morceaux et ...     tomato    6.0
260  fr:Pulpe de tomates fraîches avec morceaux et ...     tomato    6.0
263  fr:Pulpe de tomates fraîches avec morceaux et ...     tomato    6.0
22   fr:Pulpe de tomates fraîches avec morceaux et ...     tomato    6.0
264                     fr:Pulpe de tomates italiennes     tomato    6.0
259  fr:Pulpe de tomates fraiches avec morceaux et ...     tomato    6.0
173  fr:pulpe de tomates fraîches avec morceaux et ...     tomato    6.0

In [ ]:
###########################################
# MERGE TOMATO into INGREDIENTS
###########################################

In [112]:
ing_tomato = ing.merge(tomato, left_on='id_ingredient', right_on='id_ingredient', how='left')

In [100]:
ing_tomato

,O_EAN13,id_ingredient,has_sub_ingredients,sub_ingredients,text,percent_min,percent_max,percent,rank,product_name_fr,unknown_ingredient,id_language,id_ing_sub_ing,sub_ing_dict,sub_ingredients_id,sub_ingredients_fr,sub_ingredients_text,ing_id_sub_ing_id,NORMALISED,SCORE
0,10127780,fr:coulis-de-tomates,NaN,NaN,Coulis de Tomate,78.900,78.900000,78.9,1.0,sauce tomate et aubergines grillées,1,fr,NaN,NaN,NaN,NaN,NaN,fr:coulis-de-tomates,tomato,4.0
1,10127780,en:aubergine,NaN,NaN,aubergines,9.700,9.700000,9.7,2.0,sauce tomate et aubergines grillées,0,en,NaN,NaN,NaN,NaN,NaN,en:aubergine,NaN,NaN
2,10127780,en:extra-virgin-olive-oil,NaN,NaN,huile extra-vierge d'olive,3.900,3.900000,3.9,3.0,sauce tomate et aubergines grillées,0,en,NaN,NaN,NaN,NaN,NaN,en:extra-virgin-olive-oil,NaN,NaN
3,10127780,en:onion,NaN,NaN,oignons,1.875,3.900000,NaN,4.0,sauce tomate et aubergines grillées,0,en,NaN,NaN,NaN,NaN,NaN,en:onion,NaN,NaN
4,10127780,en:carrot,NaN,NaN,carottes,1.200,3.175000,NaN,5.0,sauce tomate et aubergines grillées,0,en,NaN,NaN,NaN,NaN,NaN,en:carrot,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
39109,9556041612555,en:yeast-extract,NaN,NaN,EXTRAIT DE LEVURE,0.000,5.945048,NaN,14.0,Curry rouge thaï,0,en,NaN,NaN,NaN,NaN,NaN,en:yeast-extract,NaN,NaN
39110,9556041612555,en:cardamom,NaN,NaN,CARDAMONE,0.000,5.487736,NaN,15.0,Curry rouge thaï,0,en,NaN,NaN,NaN,NaN,NaN,en:cardamom,NaN,NaN
39111,9556041612555,en:cumin-seeds,NaN,NaN,CUMIN,0.000,5.095755,NaN,16.0,Curry rouge thaï,0,en,NaN,NaN,NaN,NaN,NaN,en:cumin-seeds,NaN,NaN
39112,9556041612555,fr:FEUILLES DE CITRON VERT KAFFIR,NaN,NaN,FEUILLES DE CITRON VERT KAFFIR,0.000,4.756038,NaN,17.0,Curry rouge thaï,1,fr,NaN,NaN,NaN,NaN,NaN,fr:FEUILLES DE CITRON VERT KAFFIR,NaN,NaN
39113,9556041612555,en:pepper,NaN,NaN,POIVRE,0.000,4.458786,NaN,18.0,Curry rouge thaï,0,en,NaN,NaN,NaN,NaN,NaN,en:pepper,NaN,NaN

In [78]:
ean_tomato_ing=[]
for ean in O_EAN13_U :
    temp = ing[ing['O_EAN13'] == ean]
    temp_tomato=temp[temp['NORMALISED']=='tomato']
    if temp.shape[0]!=0:
        print(temp_tomato.shape[0])
        #tomato_ing.append(ean)
        #for i in range(len(temp_tomato)):
        #    tomato_ing.append(temp['NOTATION'])

KeyError: 'NORMALISED'

In [ ]:
###########################################
# IMPORT INGREDIENTS FEATURES INTO PROD
###########################################

In [122]:
prod['basil']=prod['O_ingredients_text'].apply(lambda row: 1 if ('basil' in str(row)) else 0 )

inprod['basil']

0       0
1       0
2       0
3       0
4       0
       ..
3974    0
3975    0
3976    0
3977    0
3978    0
Name: basil, Length: 3979, dtype: int64

In [125]:
ing_to_feature=['basil','sugar','amidon','carrot','flavouring', 'preservative','thickener']
for ing in ing_to_feature:
    prod[ing]=prod['O_ingredients_text'].apply(lambda row: 1 if (ing in str(row)) else 0 )

In [126]:
prod

,O_EAN13,O_product_name_fr,O_product_name,O_brands,O_brands_tags_str,O_brands_tags,O_serving_size,O_serving_quantity,O_countries_hierarchy,O_cities_tags,...,I_CATEGORY,I_Ventes_Volume_2018,I_Ventes_Volume_2019,basil,sugar,amidon,carrot,flavouring,preservative,thickener
0,87157215,Tomato Ketchup Heinz Ouverture En Bas,Tomato Ketchup Heinz Ouverture En Bas,Heinz,['heinz'],['heinz'],NaN,NaN,['en:france'],NaN,...,NaN,NaN,NaN,0,0,0,0,0,0,0
1,50157846,Heinz Squeeze Sauce Salade Cream,Heinz Squeeze Sauce Salade Cream,Heinz,['heinz'],['heinz'],15 g,15.0,['en:france'],[],...,NaN,NaN,NaN,0,0,0,0,0,0,0
2,87157635,Tomato Ketchup,Tomato Ketchup,Heinz,['heinz'],['heinz'],NaN,NaN,['en:france'],[],...,NaN,NaN,NaN,0,0,0,0,0,0,0
3,13000001014,Organic Tomato Ketchup,Organic Tomato Ketchup,Heinz,['heinz'],['heinz'],NaN,NaN,['en:france'],NaN,...,NaN,NaN,NaN,0,0,0,0,0,0,0
4,13000526807,Heinz 57 Sauce,Sauce,Heinz,['heinz'],['heinz'],1 Tbsp (17 g),17.0,"['en:france', 'en:united-states']",NaN,...,NaN,NaN,NaN,0,0,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3974,n,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.0,0.0,0,0,0,0,0,0,0
3975,n,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.0,0.0,0,0,0,0,0,0,0
3976,n,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.0,0.0,0,0,0,0,0,0,0
3977,n,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.0,0.0,0,0,0,0,0,0,0
3978,n,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.0,0.0,0,0,0,0,0,0,0

In [120]:
prod['O_ingredients_text'] = prod['O_ingredients_text'].apply(lambda row : row.strip())
check=('basil' in prod['O_ingredients_text'])
check

AttributeError: 'float' object has no attribute 'strip'

In [ ]:
O_ingredients_text                                         2542 non-null object
O_ingredients

In [129]:
pwd

'/Users/alexei/Desktop/italians_do_it_better/O_OPENFF'

In [130]:
#Save O_PROD_FINAL with ingredeint features
prod.to_csv('../PRODUCT_FEATURIZED.csv')
prod.to_excel('../PRODUCT_FEATURIZED.xlsx')